### ISSUE TITLE
No Data from Sensors?

### ISSUE THREAD

**Issue by mikerjensen** [opendata-stuttgart/sensors-software#1002]
<body text>Hi, Just set up my first airRohr sensor kit according to the instructions here: https://sensor.community/en/sensors/airrohr/
Unfortunately all is working except no sensor data  from either of the sensors it seems. I checked voltage on the SDS011 board  - - 5.1v (red led pulses about once a second, fan is on).  I have tried both the standard and the beta firmware, same result. I configured  the ESP board before adding the sensors. Pins all look well seated. Sensor is registered on the sensor.community,  ID is 6434359. Wifi data is visible on the Madavi page, but not sensor data. Some debug data below. Any suggestions?
thanks much. </body text>
-----
![AScreenshot_2023-08-24-21-00-18-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/opendata-stuttgart/sensors-software/assets/6131450/652b5ca9-26aa-4b11-91ee-788abd333abb)
![BScreenshot_2023-08-25-09-35-14-59_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/opendata-stuttgart/sensors-software/assets/6131450/9687568c-94f4-4a2f-a8da-d30a68a99cde)
![CScreenshot_2023-08-25-09-36-14-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/opendata-stuttgart/sensors-software/assets/6131450/8f3a9d2d-0108-4431-9477-f940b672a2b5)

**Comment by Petarkir2000** [comment]
Check again wiring!

**Comment by mikerjensen** [comment]
Thanks Petarkir2000, I have the latest pre-built wired version, so i haven't done any home-brew wiring. I have double-checked and re-seated all the connectors again (see photo below), but the problem persists.
![wiring](https://github.com/opendata-stuttgart/sensors-software/assets/6131450/dda7a255-2d7c-47e6-bb5d-ab260b39a862)

**Comment by mikerjensen** [comment]
Ah well that is encouraging, I  will check. The plugs can only go in to their sockets in one configuration and in one direction, so I didn't really look at the wiring diagram. I guess the plugs were mis-wired in the first place before they were given to me.

**Comment by Petarkir2000** [comment]
See the above scheme!

**Comment by mikerjensen** [comment]
You were right! the cable order in the 6pin connector attached to the NodeMCU was reversed. I carved away the plastic on one side of the socket so i could twist the plug 180degrees, and it's working now!

**Comment by Petarkir2000** [comment]
Glad this helped you!

**Comment by pjgueno** [comment]
Congratulations!
