### ISSUE TITLE
SDS011 ID issue

### ISSUE THREAD

**Issue by PetkanDivaka85** [opendata-stuttgart/sensors-software#1008]
Hello!

I just added a sensor on a go! Nothing soldered, nothing insulated ,so of course after two days of working wind came up ,and moved it enough just to short the connections. I then insulate the connections, and got it going again. After two hours just stops ,no internet connection , no fan working , no nothing, after restart Wifi came up I can connect to it, but that's it. I tried reflashing NODE module and everything , still nothing. Then I tried to make another account and deleting sensor from https://devices.sensor.community , and now I can't register the deleted sensor. Is there a way to change ID of the sensor, or why the https://devices.sensor.community doesn't want to delete it completely , so that I can register it again.

Please help! 

Best regards Petko

**Comment by ricki-z** [comment]
@PetkanDivaka85 could you please send this request to tech (@) sensor.community?
We need some of the registered informations  even after "deleting" a registration, i.e for our archive. So we can't really delete the complete informations directly.
