### ISSUE TITLE
Senden an apis --> https funktioniert nicht?

### ISSUE THREAD

**Issue by Esp2use** [opendata-stuttgart/sensors-software#1011]
![grafik](https://github.com/opendata-stuttgart/sensors-software/assets/121380199/05559384-a339-4c39-b099-62d21c98170f)

![grafik](https://github.com/opendata-stuttgart/sensors-software/assets/121380199/dcf36378-2b0e-4ad9-9152-545d76abb631)

ohne https funktioniert es wohl

**Comment by pjgueno** [comment]
Please send the firmware version. Until a few weeks ago, I was in https. Can you paste the USB logs ?

**Comment by Esp2use** [comment]
![grafik](https://github.com/opendata-stuttgart/sensors-software/assets/121380199/0bdece3b-6b01-44c5-9e76-e430971194bf)
![grafik](https://github.com/opendata-stuttgart/sensors-software/assets/121380199/4efac68c-bdcf-4d69-a32b-b8391d0e4472)

Das hier kam jetzt auch noch hinzu:
![grafik](https://github.com/opendata-stuttgart/sensors-software/assets/121380199/f0143ded-061a-4286-bed2-4d79f27c857e)

**Comment by ricki-z** [comment]
Aktuell sind auf den Servern wieder funktionierende Zertifikate installiert.
In Kürze sollte es dann ein Firmwareupdate geben, das das Problem längerfristiger behebt.
