### ISSUE TITLE
HTTPS for sensor.comunity will not work anymore

### ISSUE THREAD

**Issue by czechdude** [opendata-stuttgart/sensors-software#1013]
If you wonder why your all sensors do not connect to sensor. comunity API via HTTPS since Wed 13, March 2024, here is why:
Due to change in certificate type the HTTPS connection for sensor.community will not work anymore until some good guy changes it here.

The source:

https://forum.sensor.community/t/data-upload-stopped/2651

**Comment by ricki-z** [comment]
At the moment HTTPS should work again. We are working on an OTA update
