### ISSUE TITLE
Request: Support for PMS7003

### ISSUE THREAD

**Issue by Adorfer** [opendata-stuttgart/sensors-software#103]
http://aqicn.org/sensor/pms5003-7003/de/ seems to support 10, 2.5 and 1.0 . 
In plus it's not only smaller, but promises as PMS7003 higher MTBF due to optimized airflow avoiding dusting. 

![grafik](https://user-images.githubusercontent.com/10302493/28223921-8a915006-68cd-11e7-81b9-30c86154c835.png)
![grafik](https://user-images.githubusercontent.com/10302493/28223927-8f4336dc-68cd-11e7-9539-b79458b09b37.png)

(perhaps it is already a drop-in, but the extra 1.0 scale -in case it works- will probably need some adaptation.)

**Comment by Adorfer** [comment]
sample code see 
https://github.com/MartyMacGyver/PMS7003-on-Particle/blob/master/pms7003-photon-demo-1/pms7003-photon-demo-1.ino

**Comment by ricki-z** [comment]
New version NarZ-2017-095 with support for Plantower Sensors is online. Sensors should get this Version via auto update. Please check this version and close this issue if it's okay. PMS7003 is connected the same way as the SDS011.

**Comment by ricki-z** [comment]
@Adorfer actual firmware version is supporting all Plantower dust sensors.
Can we close this issue?

**Comment by Adorfer** [comment]
Thank you!

**Comment by Adorfer** [comment]
Just for note: works now fine: 
![grafik](https://user-images.githubusercontent.com/10302493/30673528-15e8e84a-9e74-11e7-8aa7-b5e9f26ed607.png)

**Comment by dokape** [comment]
@Adorfer mein PMS7003 zum testen ist heute gekommen.
Du hast auf den Bildern ein Kabel mit Platine von 2,54mm Raster auf das 1,27mm Raster vom PMS-Stecker.
War das bei dir dabei? Bei mir ist nur ein "Stecker" zum Auflöten auf eine Platine dabei.

**Comment by Adorfer** [comment]
Bei mir waren sowohl besagte Adapterplatine mit den Kabeln (war ein Stecker dran, habe ich abgeschnitten, um auf den Wemos-Mini zu löten, zum Stecken passt die Reihenfolge nicht ;-)

Und es war auch dieser winzlings-Stecker (siehe eingekreist im Bild) dabei. 
Was der Lieferant mitliefert: ist je nach Anbieter verschieden. Einzeln sind die Adapter-Platinen jedoch unverschämt teuer. (5 USD?)
![grafik](https://user-images.githubusercontent.com/10302493/31278500-74dd04c0-aaa5-11e7-815b-61b042c02d00.png)

**Comment by Adorfer** [comment]
P.S: https://www.aliexpress.com/item/The-G7-switch-board-with-cable-for-laser-sensor-PMS7003-PM2-5-particles/32780006665.html
