### ISSUE TITLE
4294967 Sekunden bis zur Messung

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/sensors-software#106]
Witziger Bug 
Ist die Messung gerade abgeschlossen und man lädt die Seite mit den Sensorwerten genau in dem Moment direkt von der /values - Seite des Sensors, wird ein vollkommen wirrer Wert ausgegeben. 
Beim nächsten reload der Seite ist alles OK. 

![screenshot_20170721-165225](https://user-images.githubusercontent.com/22255381/28469168-b238cf2c-6e35-11e7-8435-b457c358b0f8.png)

**Comment by ricki-z** [comment]
Ich habe eine dunkle Ahnung, woher das kommt. Ausgegeben wird:
round((sending_intervall_ms - (act_milli - starttime)) / 1000.0)
sending_intervall_ms ist konstant, act_milli wird jeweils zum Beginn eines Schleifendurchlaufs auf die aktuelle 'Zeit' gesetzt. starttime wird einmal in setup() auf die aktuelle 'Zeit' gesetzt, dann jeweils direkt nach dem Senden der Daten.
Und danach erfolgt noch einmal ein Abarbeiten der Page requests. Ich verschiebe jetzt mal das zweite Setzen von starttime hinter die page requests. Dann sollte es eigentlich nicht mehr vorkommen. Kann aber dauern, bis das auf allen Sensoren ankommt ;-)

**Comment by dokape** [comment]
Oder dirty sowas:
if Roundwert > Messintervall, dann Roundwert = 0

Fehler ist reproduzierbar, wenn man genau in der abgelaufenen Sekunde ein page-reload macht :-) 
Aber wer macht das schon. 

Die Messwerte liegen ja vor, die erste Messung ist komplett durch. 
Man könnte dann auch einfach die Anzeige der roten Schrift unterdrücken.
If Messung = fertig, dann nix Wartehinweis. 

If Not Messwert, dann Wartehinweis.
Wenn das erste mal Messwerte vorliegen, dann gibts auch keinen Wartehinweis mehr. Dann kann da drinstehen was will.

Wer mal Software-QS gemacht hat, findet überall alle Fehler. ;-)

**Comment by ricki-z** [comment]
Das mit If not Messwert war ja drin. Es gibt ein Flag, das nach der ersten Messung gesetzt wird. Leider war aber auch hier die Verarbeitung der Page requests an einer ungünstigen Stelle.

**Comment by dokape** [comment]
![messung](https://user-images.githubusercontent.com/22255381/30034158-c153c696-919f-11e7-84a6-442b9771345b.PNG)

Die Änderung vom 21.7. war nicht hilfreich.

**Comment by dokape** [comment]
NRZ-2017-099
Tritt nicht mehr auf. Steht jetzt sauber da: 
0 Sekunden bis zur ersten Messung.
Gefolgt (nach reload) von
0 Sekunden seit der letzten Messung und Display der Werte. 

*closed*
