### ISSUE TITLE
/values should show time/date of values

### ISSUE THREAD

**Issue by jms72** [opendata-stuttgart/sensors-software#111]
For the current values under /values it should be shown from what time these values were collected (if there's an issue with absolute time, it's perfectly fine to say "xx seconds/minutes ago")

**Comment by Adorfer** [comment]
this implies the sensor knows a valid time. 
(i do not know if keeping an ntp client is really neccesary on a device which does not store any data locally anyway)

**Comment by ricki-z** [comment]
The NodeMCU doesn't have a RTC and NTP is crashing with the rest of our firmware. So we can only print something like "xx seconds/minutes ago". I will try to insert this in one of the next versions.

**Comment by ricki-z** [comment]
The next version will show the time since last measurement under /values and as an entry in /data.json .

**Comment by ricki-z** [comment]
New Version is online. Sensors will auto update, if this isn't disabled. Please look at the values page and the /data.json if this is okay for you.
Don't forget to close the issue f it's okay.

**Comment by jms72** [comment]
Thanks so much for the quick turnaround. Due to travels I will only have
opportunity to check in about three weeks.

Am 17.08.2017 4:44 nachm. schrieb "Rajko Zschiegner" <
notifications@github.com>:

**Comment by jms72** [comment]
Confirming it works great
