### ISSUE TITLE
simple way to get sensor current values?

### ISSUE THREAD

**Issue by pauledd** [opendata-stuttgart/sensors-software#117]
Hi

Is there a simple way to get the current sensor values in bash directly from the device without asking any external servers?

For example to get current temperature of my BME280 I use this "complicated" command:

`curl -s http://192.168.1.150/values | awk -F"tur</td><td class='r'>|&nbsp" '{print $6}'`
is there a more elegant way?

**Comment by ricki-z** [comment]
You can get the values as JSON. The URL is http://192.168.1.150/data.json .

**Comment by pauledd** [comment]
great, thanks!
