### ISSUE TITLE
Bme 280 Support

### ISSUE THREAD

**Issue by miloit** [opendata-stuttgart/sensors-software#119]
Hello, how is the implementation done? Simply connect?

**Comment by ricki-z** [comment]
You need to configure the used sensors. So if you use the BME280 and not the DHT22 you have to enable the BME280 and disable the DHT22 in the configuration. Also you should tell us the used sensors if you 'register' the sensor.

**Comment by dokape** [comment]
@miloit: 
Is your question answered? 
Any requirement for further discussion?
Can you close this issue?

**Comment by miloit** [comment]
Yes, thanks I will close this issue
