### ISSUE TITLE
Include GPS positions

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/sensors-software#12]
For mobile sensors, there should be a GPS position included with the data.
In that case, GPS lat lon alt PDOP fixtype, maybe RMS info (azimuth, speed) and GPS time might be of interest. All these values are measurement values (define a sensor accordingly).

Possible approaches:
- the GPS sends messages in parallel (e.g. push lat lon with same nodeID), maybe the easiest/most flexible way (nodeID needs to be configurable).
  - generally no direct sync between measurements, needs to be handled by analysis
- The GPS position is directly parsed by node (connect to serial, parse NMEA messages, at least RMC/GGA messages)
  - regularly handle serial (certain interrupt intervals?), assemble messages, check CRC, tokenize
  - see https://github.com/adafruit/Adafruit-GPS-Library/ http://arduiniana.org/libraries/tinygpsplus/
  - needs some CPU cycles/interrupts
- the GPS position can be received by node via network (e.g. from a gpsd) and be added/sent

Hardware:
- https://www.sparkfun.com/pages/GPS_Guide
- https://www.adafruit.com/products/746
- NEO-6M Ublox http://www.instructables.com/id/Arduino-Ublox-GPS/
- http://www.mr-lee-catcam.de/pe_cc_i6.htm

**Comment by dokape** [comment]
the actual firmware NRZ-2017-099 supports neo6m connected to the sensor.
GPS-Data is transmitted with the sensor-data.

Is there any requirement for further discussion or can this issue be closed?
