### ISSUE TITLE
Config-Änderungen ersetzten Auth-Passwort

### ISSUE THREAD

**Issue by lemmingz** [opendata-stuttgart/sensors-software#121]
Werden nachträglich Änderungen an der Config gemacht (bspw. das Hinzufügen der OpenSenseMap-ID), wird durch das Speichern das Basic-Auth-Passwort auf x-mal * gesetzt, wobei x für die Anzahl der Zeichen des ursprünglichen Passworts entspricht.

Der Fehler liegt hier in der form_password-Funktion die das Passwort durch Sternchen ersetzt. Da dieser Wert dann aber der Value des Inputs ist wird das Passwort entsprechend geändert.

**Comment by ricki-z** [comment]
Wenn das Passwort nur aus Sternchen besteht, wird es nicht neu gesetzt. Dadurch sollte das von dir beschriebene Verhalten eigentlich nicht vorkommen. Siehe dazu die Zeilen 1128 und folgende.
Damit soll verhindert werden, das man aus dem Konfig-Formular das Passwort im Klartext auslesen kann.

**Comment by lemmingz** [comment]
Ja, für das WLAN-Passwort findet der Check statt, aber nicht für das www_password. Ich habe mich damit gestern für eine Weile vom Sensor ausgesperrt.

**Comment by ricki-z** [comment]
Alles klar, danke für den Hinweis. Wird gerade berichtigt. Alle anderen Passwörter sind nur Inputfelder. Dort war die Maskierung und Überprüfung nicht nötig.

**Comment by ricki-z** [comment]
Die neue, korrigierte Version NRZ-2017-096 geht gerade raus. Die meisten Sensoren sollten diese in 24 Stunden haben. Bitte testen und wenn der Fehler damit entfernt ist, den Issue bitte schließen.

**Comment by lemmingz** [comment]
Version NRZ-2017-096 kam an und der Fehler tritt nicht mehr auf. 

Vielen Dank!

**Comment by ricki-z** [comment]
@lemmingz Kannst du die Version NRZ-2017-098 testen (sollte in den kommenden Stunden auf deinem Sensor landen)? Bei mir hat es auf 2 Sensoren funktioniert, wie es sollte. Aber vielleicht habe ich irgendeine Möglichkeit übersehen.

**Comment by lemmingz** [comment]
Sieht soweit gut aus. (NRZ-2017-099)
