### ISSUE TITLE
BMP280 in den JSON und OpenSenseMap Daten fehlt der Trenn Punkt

### ISSUE THREAD

**Issue by sandboxgangster** [opendata-stuttgart/sensors-software#126]
Hallo, 

In meinen Sensordaten fehlt in der JSON Datei und in den Opensensemap Daten der Punkt für die Kommastellen also statt z.b. 1013.35 wird 101335 beim Luftdruck ausgegeben im Web interface ist der wert richtig.

Firmware ist die Akktuelle: NRZ-2017-097
mfg

**Comment by ricki-z** [comment]
Hallo,
wir senden alle Daten als 'Roh-Daten'. Der BME280 liefert Pascal zurück, dieser Wert wird dann auch so an die Server geschickt. Lediglich das Web-Interface stellt den gebräuchlicheren Hektopascal-Wert dar. Eine Verarbeitung und Umrechnung sollte immer erst auf den Servern geschehen.

**Comment by sandboxgangster** [comment]
Ok, danke dann war das ein Denkfehler meinerseits.
