### ISSUE TITLE
Feature request: add servo driving functionality

### ISSUE THREAD

**Issue by intui** [opendata-stuttgart/sensors-software#134]
I'd like to attach a servo Motor to drive an arrow visualizing the Feinstaub value and attach it to the house so it is visible for the cars that drive by.

**Comment by dokape** [comment]
What about a stand-alone solution? 
An additional nodeMCU with servo-driver that pulls the values by json-data from the sensor? 
Try yourself: 
http://<Your-Sensor-ip>/data.json

**Comment by ricki-z** [comment]
We have to focus on functionality needed more than once. The available flash space is very limited. By now we use 86 percent of (firmware) flash and 59 of RAM.

**Comment by dokape** [comment]
is there any requirement for more discussion or can this be closed?

**Comment by intui** [comment]
ok. to close. I'll try the standalone approach. Thanks
