### ISSUE TITLE
Dependency OneWire.h missing

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/sensors-software#138]
Trying to compile the arduino firmware.
complete new setup.
used this description for setup IDE/Arduino:
https://github.com/opendata-stuttgart/sensors-software/blob/master/airrohr-firmware/Readme.md

Added the DallasTemperature lib as described. 
At compile I get this error:

C:\Users\xxx\Documents\Arduino\libraries\DallasTemperature/DallasTemperature.h:22:21: fatal error: OneWire.h: No such file or directory

 #include <OneWire.h>

The Support of Dallas OneWire Sensor was added 
NRZ-2017-095 online as update since 2017-08-17

Is this the correct additional lib?
https://github.com/PaulStoffregen/OneWire

The compile runs through with this lib.

**Comment by ricki-z** [comment]
Dependency included.
