### ISSUE TITLE
Build with updated Expressif-Libraries for KRACK (WPA2/ieee80211r etc)

### ISSUE THREAD

**Issue by Adorfer** [opendata-stuttgart/sensors-software#150]
Just to document it here: I assume that the upcoming (binary) releases will be made with the updated Libraries for Arduino/ESP8266.
https://github.com/esp8266/Arduino/issues/3725

**Comment by dokape** [comment]
Arduino lib updated

https://github.com/esp8266/Arduino/issues/3725

**Comment by ricki-z** [comment]
The updated version is 2.4.0-rc2 only. Seems we need to wait for the official release of version 2.4.

**Comment by dokape** [comment]
AS I'm not a developer and not very familiar with the ArduinoIDE, I'm not shure which libraries and where and how they have to be updated in arduino to Compile and flash. :-)

**Comment by dokape** [comment]
Is the new ESP8266-Librarie (KRACK)  just used for compiling the source? '

**Comment by ricki-z** [comment]
And again: latest ESP8266 library with KRACK patches is RC1 (release candidate)
'Normal' development steps:
Alpha: including new features and fixes, may be very unstable
Beta: mostly feature complete, for testing and bug fixing
Release candidate: most bugs removed, should be ready for release, but there may be bugs, that weren't found until now.
Release: the finished and published version

**Comment by reibuehl** [comment]
I thought that RC2 is the one with the fixes??

**Comment by ricki-z** [comment]
Latest ESP8266 library with KRACK patches is RC2 (release candidate)
Please look at: https://github.com/esp8266/Arduino/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22+milestone%3A2.4.0
Many open issues for this version ...

'Normal' development steps:
Alpha: including new features and fixes, may be very unstable
Beta: mostly feature complete, for testing and bug fixing
Release candidate: most bugs removed, should be ready for release, but there may be bugs, that weren't found until now.
Release: the finished and published version

**Comment by Adorfer** [comment]
so I understand from this statement: "an rc is not a stable release, so we will not use it for a stable airrohr either". Correct?
(if there is a different condition, I might just not have understood the reply and missed something. )

**Comment by ricki-z** [comment]
this is correct.

**Comment by ricki-z** [comment]
First test with esp8266 Arduino lib 2.4.0-RC2:
only 2% available space left in flash mem. This means around 16000 Bytes for certs and other improvements.

**Comment by tux1337** [comment]
Arduino core for ESP8266 is now in version 2.4 released (final) 

I used the esptool from 2.4 to flash NRZ-2017-099, is this anything that I have to do to ensure that the sensor use now the new library with the included KRACK patch? 

If yes: I can confirm that everything is working with 2.4

**Comment by ricki-z** [comment]
This will only flash the unmodified firmware. You need to completely recompile the source code.

**Comment by ricki-z** [comment]
Its not possible to compile a working firmware with version 2.4. Compilation with this version will end up with a non-working web config.

**Comment by HarmOtten** [comment]
When can we expect an update of the sensor-software that is compatible with ESP8266 v2.4.0?

**Comment by ricki-z** [comment]
Actual version is compatible with ESP8266 v2.4.0. Closing this issue.
