### ISSUE TITLE
Request: Auto Update for beta versions

### ISSUE THREAD

**Issue by nobels** [opendata-stuttgart/sensors-software#151]
Today i had the time to upload the beta firmware.

So i have to connect my device with USB to my Computer.
Manual upload the bin file. 

But i had this idea that we could check auto-update to latest version with (Beta-versions)

Would this be nice ?

So you would have

Version 100-BETA
Version 99 (Latest version)
Version 98

**Comment by ErikLeysen** [comment]
Sounds fine form me

**Comment by ricki-z** [comment]
The auto update for beta versions will be available in the next version, see beta branch for this.
Then you can configure the use of beta versions.

**Comment by dokape** [comment]
NRZ-2017-100-B9/10

Option is implemented, but has still error.
Produces conflict with Update (more downgrade) to stable Version.  See #169

**Comment by ricki-z** [comment]
@nobels Should work with new actual release NRZ-2018-105. Can we close this issue?
