### ISSUE TITLE
NRZ-2017-100-B6 after calling data.json next run no PM-Data is shown

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/sensors-software#162]
NRZ-2017-100-B6

If you call the /data.json page, the next run the PM-Data get lost. 
If you do nothing, the overnext run the PM-Data are shown again. 

So calling the data.json will influence the display of the PM2.5 and PM10 Data in the next mesurement-run. 

At value-Page nothing is shown.
On Display nothing is shown,
The data.json does not contain the values any more (in the runs before it was there!)

<img width="245" alt="kein-feinstaub" src="https://user-images.githubusercontent.com/22255381/32460987-c1519080-c334-11e7-9ce1-ffa314133e25.PNG">

data.json:
`{"software_version": "NRZ-2017-100-B6", "age":"64", "sensordatavalues":[{"value_type":"temperature","value":"5.60"},{"value_type":"humidity","value":"65.60"},{"value_type":"BME280_temperature","value":"5.78"},{"value_type":"BME280_humidity","value":"74.23"},{"value_type":"BME280_pressure","value":"97378.70"},{"value_type":"GPS_lat","value":"47.xxx315"},{"value_type":"GPS_lon","value":"8.xxx872"},{"value_type":"GPS_height","value":"47.74"},{"value_type":"GPS_date","value":"11/06/2017"},{"value_type":"GPS_time","value":"19:52:45.00"},{"value_type":"samples","value":"223224"},{"value_type":"min_micro","value":"263"},{"value_type":"max_micro","value":"1730019"},{"value_type":"signal","value":"-51"}]}`

Checked: Issue is not in NRZ-2017-099 (actual master)

**Comment by dokape** [comment]
NRZ-2017-100-B7

Calling the /data.json in Browser,
the next cycle / run PM-Data will not be displayed on Displays, in Web and will not be transferred to influxx, or own API.

**Comment by ricki-z** [comment]
On my node I can't replicate this. I tried this some times but every time the values were shown as expected on both the displays and the values page.

**Comment by dokape** [comment]
After doing More tests and changing setup:
I'm mit shure if calling the data.json data is the trigger.

Letting the Sensor running for some hours, a lot of SDS and DHT values are not logged/shown/transmitted
To my custom API. 
Going back to NRZ-2017-100-B4 solves the problem without changing hardware setup or config. 
So I might suggest it is based in the changes between -100-b4 and -100-b6

**Comment by dokape** [comment]
NRZ-2017-100-B10
seems to be stable. Issue cannot be replicated yet.

**Comment by ricki-z** [comment]
@dokape can we close this issue?

**Comment by ricki-z** [comment]
@dokape Should work with new actual release NRZ-2018-105. Can we close this issue?

**Comment by ricki-z** [comment]
Closed after 6 months of inactivity.
