### ISSUE TITLE
Deepsleep option

### ISSUE THREAD

**Issue by remyderuysscher** [opendata-stuttgart/sensors-software#174]
I have an ESP8266 and would like to use the deep sleep option, since mine is battery powered.

This requires a hardware modification GPIO16 needs to be tied to RST to wake from deepSleep.

A software configurable timer would be nice 5, 10, 15 min.

The function is called ESP.deepSleep(microseconds, mode) will put the chip into deep sleep. mode is one of WAKE_RF_DEFAULT, WAKE_RFCAL, WAKE_NO_RFCAL, WAKE_RF_DISABLED.

**Comment by Adorfer** [comment]
See https://github.com/opendata-stuttgart/sensors-software/issues/104

**Comment by DeeKey** [comment]
@dirkmueller please close as duplicate

**Comment by dirkmueller** [comment]
Duplicate of #104
