### ISSUE TITLE
ADAFRUIT HTU21D lib in readme.md fehlt

### ISSUE THREAD

**Issue by dokape** [opendata-stuttgart/sensors-software#176]
https://github.com/opendata-stuttgart/sensors-software/blob/beta/airrohr-firmware/Readme.md

hier ist noch die Sparkfun lib aufgeführt.

Ich gehe davon aus, es wird die Adafruit HTU21DF Library Version 1.0.1 benötigt.

**Comment by ricki-z** [comment]
Ist in der Readme geändert.
