### ISSUE TITLE
Validate user input in "host" fields

### ISSUE THREAD

**Issue by dadosch** [opendata-stuttgart/sensors-software#178]
The software should make sure, that no http:// or https:// is entered into the host fields (i.e. influx field) by the user and/or that https is not supported.

It took be 1 hour (!) to realize this...

**Comment by ricki-z** [comment]
Really??? If you configure the sensor the first time or haven't changed the entries there are example hostnames WITHOUT http:// or https://.

**Comment by dadosch** [comment]
Is it ok, if I document it in the wiki?

**Comment by ricki-z** [comment]
This would be nice. Thank you in advance.
