### ISSUE TITLE
Use web page (like config.luftdaten.info) to configure the esp8266

### ISSUE THREAD

**Issue by dadosch** [opendata-stuttgart/sensors-software#179]
I'm not sure if it is possible, but I explain what I mean:
You externalize the whole full-blown webpage (with styles+logos) to a host reachable from the internet (for example config.luftdaten.info).

On that site, you could enter the IP address of the esp8266. It then would send from the user's browser the config to a much simpler *local* interface on the esp8266.
(You still need to be on the same network to configure the esp)

**This would save quite a bit of memory.**

Only the wifi credentials must be entered directly in the esp8266. (Or use a HTML5-Offline-App)

[Cross-Origin Resource Sharing](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing) may be needed

Maybe I explained a bit weird what I mean, so here is a drawing:

![airrohr_offline](https://user-images.githubusercontent.com/12801390/34545769-5bf3d20a-f0ef-11e7-95d6-2e5280513ef9.png)

**Comment by ricki-z** [comment]
On a WPA2-enabled wifi the ESP8266 won't have an IP address until configured as it don't know the needed credentials.
So we have to implement a web page for configuration anyway. The pages, styles and logos (could be removed or made smaller) don't need so much more memory. With your solution we have to 'develop' just another piece of software/webpage that needs to be maintained.

**Comment by dadosch** [comment]
Yeah, it was just an idea to get some space on the esp8266...
