### ISSUE TITLE
Dependency on lwIP not documented

### ISSUE THREAD

**Issue by sensor-freak** [opendata-stuttgart/sensors-software#183]
It seems that the project depends on the lwIP variant "v1.4 Prebuilt". At least I could not successfully build the firmware with the variante set to v2.0. This should be noted in the configuration section of the readme (probably under "Einstellungen Arduino IDE").

**Comment by ricki-z** [comment]
The actual beta can be compiled with all lwIPs.

**Comment by ricki-z** [comment]
@sensor-freak Can we close this issue?

**Comment by sensor-freak** [comment]
I didn't check it, but I suppose that the issue is solved. So please feel free to close it.

Thank you for all!
