### ISSUE TITLE
DHT11 supported?

### ISSUE THREAD

**Issue by dominikschulz** [opendata-stuttgart/sensors-software#194]
Does the current firmware support the DHT11 as well?
I connected a DHT11 because I didn't have a spare DHT22 but the readings are completely off (~600°C and 300%RH). 

Faulty sensor or unsupported setup?

**Comment by ricki-z** [comment]
The DHT11 needs another initialization as the DHT22. This is not done in the actual firmware. So we don't support the DHT11.

**Comment by dokape** [comment]
@dominikschulz is you question answered?
Can the issue be closed? If yes, please close the issue. It's not gone. Just not active and can be found again.

**Comment by dominikschulz** [comment]
Thanks a lot, that answers my question :+1:
