### ISSUE TITLE
Offline sensors - update push URL

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/sensors-software#22]
These sensors stopped working on 1.4.2016:

sensor IDs are: 
~~36,~~ 54, 56, ~~59,~~ 76, 77, 82

see http://mqtt.opendataset.click/output_plots/plots_sensordata_overview.pdf

**Comment by mfa** [comment]
59 fixed.

**Comment by ricki-z** [comment]
36 fixed, but "offline".
comparison measurement in juelich
