### ISSUE TITLE
No "signal" in influx API data

### ISSUE THREAD

**Issue by sensor-freak** [opendata-stuttgart/sensors-software#220]
Hi,

I just noticed that the data value "signal" is not included in the (additional) InfluxDB API. Is there a valid reason for this?

If not, would someone mind to include the value in the data string? It seems that there are only two adjustments have to be made in function create_influxdb_string():

- remove the term "- 1" in the condition of the for loop
- change the term "- 2" to "- 1" in the if statement where the need for a comma is checked.

Kind regards

**Comment by ricki-z** [comment]
The reason: signal value was included only for 'debbuging' wifi problems.
We will include this in the next release .

**Comment by ricki-z** [comment]
This should work with actual beta.

**Comment by ricki-z** [comment]
@sensor-freak signal should be included in InfluxDB data. Can we close this issue?

**Comment by sensor-freak** [comment]
Fixed with commit 00d3d6bfe175897ebff2ee36e8bf804309975f8e, works as expected now.
