### ISSUE TITLE
SSID with ' character not displayed

### ISSUE THREAD

**Issue by Dumbaz** [opendata-stuttgart/sensors-software#228]
The connection to my WLAN works, but in the webserver's mask only characters before the ' symbol are displayed.

To reproduce: use a Wifi Name with single quotes ' in it.

Image
![image](https://user-images.githubusercontent.com/6582804/41809503-ff32e2b4-76ee-11e8-9511-dbd33c76aeb5.png)

What is supposed to be displayed: M'network

**Comment by ricki-z** [comment]
This should work with actual beta.

**Comment by ricki-z** [comment]
@Dumbaz Should work with new actual release NRZ-2018-105.

**Comment by ricki-z** [comment]
@Dumbaz can we close this issue?

**Comment by Dumbaz** [comment]
Sorry for not responding, will test later today!

**Comment by Dumbaz** [comment]
This issue can be closed, it is working now 👍
