### ISSUE TITLE
GPIO PINSs <-> nodemcu PINs (Dx) mapping

### ISSUE THREAD

**Issue by ricki-z** [opendata-stuttgart/sensors-software#23]
Hi marwe,
the mapping GPIO <-> Pins is defined in Arduino.h (via pins_arduino.h and variants). I.e. you can use D1 to access Pin 1. This saves space for other variables and reduces the size of the compiled binary.

Rajko

**Comment by Marwe** [comment]
Ah thanks, saw it in your code already. I often need the table for translation, but could be a comment ;)
