### ISSUE TITLE
OLED display's brightness issue

### ISSUE THREAD

**Issue by stewecar** [opendata-stuttgart/sensors-software#239]
Hello,
I have noticed in the latest firmware a less brightness of the OLED display.
It could be a problem of my oled but it seems it appeared with the last update.
Thanks.

**Comment by ricki-z** [comment]
We don't set any brightness values in the firmware. The beta tests with different displays also did not show a difference in brightness. So it is most likely an issue with your OLED display.

**Comment by stewecar** [comment]
Thanks!
