### ISSUE TITLE
Indices array must be initialized with constant value

### ISSUE THREAD

**Issue by LuchtwachtersDelft** [opendata-stuttgart/sensors-software#251]
In `webserver_wifi()` there's a line 

`int indices[n];`

Visual Studio with [vMicro](https://www.visualmicro.com/) shows an error about that line: `expression must have a constant value`.

I wonder if it can be ignored because it's handled by the compiler. Or maybe it causes a hidden runtime error?

It can be written more neatly as 

```
int* indices = new int[n];
...
delete[] indices;
```

... although generally the recommendation is using a vector instead. But since vector isn't included now that would increase the file size.

**Comment by ricki-z** [comment]
Is merged to beta branch.
