### ISSUE TITLE
DHT22 sensor stops working at 0.00 UTC

### ISSUE THREAD

**Issue by leo95nf** [opendata-stuttgart/sensors-software#255]
Hello,
As I wrote in the title, every day at 0.00 UTC the sensor stops working. (https://www.madavi.de/sensor/graph.php?sensor=esp8266-11648447-dht)
I tried to change wires, to change sensor, to restart but I can't resolve it. Is it a bug?
Thank you

**Comment by dirkmueller** [comment]
It looks like this sensor is now offline much more often. Can you please tick the 'use beta firmware' option and report back? We have made several stability fixes there.

**Comment by dirkmueller** [comment]
Please reopen after above has been tried.
