### ISSUE TITLE
BMP280 stopped working at the same time on multiple NodeMCUs

### ISSUE THREAD

**Issue by YNedderhoff** [opendata-stuttgart/sensors-software#256]
I have 4 NodeMCUs with BMP280 sensors, some of them additionally also have others. I store data in an InfluxDB instance on a Raspberry Pi. On Sept 4th at the same time data from all sensors stopped appearing in my database. Data from other sensors continues to be there.

I didn't do a lot of debugging, yet, but instead wanted to ask if there are any known issues, perhaps through a software update? The devices seem to run `NRZ-2018-109`. Or if that's not the case, if you have any debugging advice beyond restarting every involved device.

**Comment by LuchtwachtersDelft** [comment]
Can confirm the Madavi.de graphs stopped at 00:00 UTC 5 Sept for my NodeMCU with a BME280, while my other NodeMCU with DHT22 kept going.

![image](https://user-images.githubusercontent.com/37801654/45585921-a8969180-b8ed-11e8-8696-c4199d5ac06e.png)

![image](https://user-images.githubusercontent.com/37801654/45585923-b2b89000-b8ed-11e8-8d89-a59c6b186085.png)

Check the CSV archive on that day. No data between 2018/09/04 23:58:31 and 2018/09/05 09:14:26.

https://www.madavi.de/sensor/csvfiles.php?sensor=esp8266-{Your NodeMCU ID}

Related? https://github.com/opendata-stuttgart/sensors-software/issues/255

**Comment by YNedderhoff** [comment]
Thanks, that was the reason indeed.
