### ISSUE TITLE
Missing Library in Readme.md

### ISSUE THREAD

**Issue by HobbyIngenieur** [opendata-stuttgart/sensors-software#27]
Hi, 
after adding all recommended libraries, compilation ended up with:
"Adafruit_Sensor.h: No such file or directory"
After adding "Adafruit Unified Sensor", compilation went through without errors.

Kind regards and a happy new year ;-)
Jo

**Comment by ricki-z** [comment]
Hi,
I've added the missing library. Thanks for this hint.
Rajko
