### ISSUE TITLE
measurement intervals < 15 seconds not working

### ISSUE THREAD

**Issue by ricki-z** [opendata-stuttgart/sensors-software#277]
This needs a code review.
On intervals shorter than 15 seconds no data is shown or transmitted for pm sensors.

**Comment by jordanc365** [comment]
This actually occurs for measurement intervals <20 seconds.
This is becasue the sensor warmup time is 20 seconds.

**Comment by jordanc365** [comment]
The reason this occurs is that the measurement interval needs to be greater than the sum of the reading time (5 seconds) and the warmup time(15 seconds) :. the default code crashes if you try to sample in intervals <20 seconds. 
You can change these values in the code yourself.
Hope this helps!

**Comment by dirkmueller** [comment]
Better description / duplicate in #426 - closing this one
