### ISSUE TITLE
Request: Support for Sensirion SPS30 

### ISSUE THREAD

**Issue by OGVT** [opendata-stuttgart/sensors-software#332]
Hello everyone, 

Is the Sensirion SPS30 already supported by the current software or will support be possible in the future? 

https://www.sensirion.com/de/umweltsensoren/feinstaubsensoren-pm25/

I have here two new SPS30 which I'd like to test if possible.

Thx

**Comment by ricki-z** [comment]
If someone could send me one I would include it in our firmware. I have the documentation but no test example.

**Comment by OGVT** [comment]
That's great! Thx. I could send you one - send me your address by pm.

**Comment by ricki-z** [comment]
It's work in progress. Test samples arrived short before xmas, so there were only limited time to implement something.

**Comment by freemann** [comment]
Great to hear and looking forward to the results!

**Comment by stewecar** [comment]
It seems a good sensor with a nice autoclean function..
Anyway it is not cheap at all..don't know how much is "compatible" with
luftdaten project :)

Il giorno mer 9 gen 2019, 11:03 Marco <notifications@github.com> ha scritto:

**Comment by michapr** [comment]
Any news?
Have sensor here in my local project, it is running fine.
Agree, it is not the cheepest, but seems to be high quality sensor.

**Comment by LuchtwachtersDelft** [comment]
There's a library for the SPS30, but you need to increase the buffer in wire.h to read all data on a NodeMCU.

https://github.com/paulvha/sps30

Note the documentation in sps30.odt.

**Comment by dirkmueller** [comment]
This has been implememented in  NRZ-2019-125, please close
