### ISSUE TITLE
Request: Support for Sensirion SHT31

### ISSUE THREAD

**Issue by OGVT** [opendata-stuttgart/sensors-software#334]
Hi,

Currently I am testing the two sensors BHT22 and BME280. Especially in the current season we have a very high air humidity here. It occurs to me that with RH > 90% both sensors output very different values. The BHT22 saturates relatively fast and shows only 100%, while the BME280 hardly ever exceeds 90%. 

My Davis weather station uses a Sensirion SHT31. It seems to handle the high humidity much better. Will it be possible to operate a SHT31 (i2c) via the NodeMCU ESP8266 in the future?

CS, R

https://www.sensirion.com/en/environmental-sensors/humidity-sensors/digital-humidity-sensors-for-various-applications/

https://de.aliexpress.com/wholesale?catId=400103&initiative_id=AS_20181125114041&SearchText=sht31

**Comment by ricki-z** [comment]
@OGVT should work with the actual release version. Could you please close this issue if it's okay?

**Comment by OGVT** [comment]
Thank you very much!

**Comment by OGVT** [comment]
Hi @ricki-z, can't see the SHT31 in the config. Which sensor type must I select in the configuration to address the SHT31?, BR, R

**Comment by ricki-z** [comment]
Sorry thats on the beta branch, should be available when switching to beta versions or with next release. mixed up with other sensors added (noise, sps30)

**Comment by OGVT** [comment]
Hi @ricki-z, can't find it in the latest_beta.bin. Should it be there?

**Comment by ricki-z** [comment]
Which version number is shown on the sensor internal website?

**Comment by OGVT** [comment]
Hi Rajko,

 

NRZ-2019-125-B1

 

 

 

 

Beste Grüsse

Roger

 

 

Von: Rajko Zschiegner <notifications@github.com> 
Gesendet: Dienstag, 12. November 2019 00:23
An: opendata-stuttgart/sensors-software <sensors-software@noreply.github.com>
Cc: Roger <roger.spinner@ogvt.org>; State change <state_change@noreply.github.com>
Betreff: Re: [opendata-stuttgart/sensors-software] Request: Support for Sensirion SHT31 (#334)

 

Which version number is shown on the sensor internal website?

**Comment by ricki-z** [comment]
This is the latest release version.
If you activate "use beta" on the sensor internal website the sensor should update to the latest beta.

**Comment by OGVT** [comment]
works great!

 

Thank you.

 



BR, R

Von: Rajko Zschiegner <notifications@github.com> 
Gesendet: Mittwoch, 13. November 2019 13:07
An: opendata-stuttgart/sensors-software <sensors-software@noreply.github.com>
Cc: Roger <roger.spinner@ogvt.org>; State change <state_change@noreply.github.com>
Betreff: Re: [opendata-stuttgart/sensors-software] Request: Support for Sensirion SHT31 (#334)

 

This is the latest release version.
If you activate "use beta" on the sensor internal website the sensor should update to the latest beta.

**Comment by dirkmueller** [comment]
Thanks for the feedback!
