### ISSUE TITLE
TLS speed

### ISSUE THREAD

**Issue by ricki-z** [opendata-stuttgart/sensors-software#336]
The latest update should also enabled TLS and certificate verification. But then the sensors needed too long to connect and to send data. The result was a large amount of open connections on the server. So I'm testing different ciphers and settings for TLS connections at the moment. This issues is for saving and publishing the results of these tests.
All test are made with a cpu frequency of 80MHz.
(Working version NRZ-2018-111: no cert verification, TLS1.1, AES256-SHA)

Connections without verification:
default secure client: TLS1.2, AES256-SHA256 -> 1000ms

Connections with verification:
default secure client: TLS1.2, AES256-SHA256 -> 1400ms to 1500ms

Background:
most webservers have a limited amount of connections they can handle.
With a connection open for 1 second we would need 1 possible connection per 150 sensors. For 6000 sensors we need 40 possible connections under ideal conditions

From Log, first line is a sensor with a firmware compiled with version 2.4.2, second was compiled with version 2.3:
`146.60.x.x [28/Nov/2018:11:17:12 +0000] "POST /data.php HTTP/1.1" 200 3287 "-" "-" 69047 TLSv1.2 AES256-SHA256`
`146.60.x.x [28/Nov/2018:11:17:31 +0000] "POST /data.php HTTP/1.1" 200 3287 "-" "-" 1728 TLSv1.2 AES256-SHA256`

Identical size of answer (3287 Byte), but the time needed is very different:
version 2.4.2: 69047 µs
version 2.3: 1728 µs
Other samples show the same ratio, so it's not a question of server usage.

**Comment by dirkmueller** [comment]
@ricki-z still an issue ?

**Comment by ricki-z** [comment]
May become an issue again with BearSSL. It's something we have to have in mind when using SSL/TLS.
But it's not a real issue so I will close this. (Can look for this later)
