### ISSUE TITLE
Custom API not receiving data

### ISSUE THREAD

**Issue by svenkubiak** [opendata-stuttgart/sensors-software#337]
Firmware: NRZ-2018-121B

I am currently trying to figure out why no data is send out to a custom API I have configured. I can actually see that there is not any data being transmitted as no request reaches the endpoint.

Offical APIs are working - Luftdaten.info and madavi are receiving data.

I have Auto-update enabled. Was there an update around 4 days ago that maybe effected custom APIs?

**Comment by ricki-z** [comment]
We need to stop the internal web server vor some seconds when the data is sent to the APIs. Please try to resend the data until the new config is saved.

**Comment by svenkubiak** [comment]
Update3: So it looks like dropping support for TLSv1.1 on my server had an effect on the API endpoint, even though I specifically did nod drop it for the sensor API endpoint. Nevertheless, data is now transmitted and handled correctly again. So error was on my side...

Sorry, for the inconvenience.

**Comment by ricki-z** [comment]
For i.e. Apache you can't limit the TLS protocols based on an endpoint, only for the whole server. And even for nginx the context is http or server. So maybe the script accessed the path on the wrong "server" (virtual, alias?)

**Comment by svenkubiak** [comment]
> For i.e. Apache you can't limit the TLS protocols based on an endpoint, only for the whole server. And even for nginx the context is http or server. So maybe the script accessed the path on the wrong "server" (virtual, alias?)

You are right. Even though it is possible to add ssl_protocols at server level you can define it only once. Looks like there is a workaround, but in general it seems not possible:
http://mailman.nginx.org/pipermail/nginx/2014-November/045733.html
