### ISSUE TITLE
WiFi configuration password input length limits

### ISSUE THREAD

**Issue by pj4y** [opendata-stuttgart/sensors-software#34]
Just leaving this here as a reminder, because I was too stupid to address it to the correct repo at the first approach.

https://github.com/opendata-stuttgart/feinstaub-map/issues/22

@ricki-z already gave me the hint, that this will be changed in the future to maxlenght=64. (This is the maximum length for WPA2 passwords).

My initial issue reads:
>Unfortunately it is not possible to enter WiFi passwords with more than 32 characters in the config form >provided with the latest firmware binary:

>https://github.com/opendata-stuttgart/sensors-software/blob/master/esp8266-arduino/ppd42ns-wificonfig-ppd-sds-dht/ppd42ns-wificonfig-ppd-sds-dht.ino.nodemcu.bin

>maxlength= "32"

>`<input name="wlanpwd" id="wlanpwd" placeholder="Passwort" >value="IWouldLikeToEnterALongPasswordHe" maxlength="32" type="password">`

**Comment by ricki-z** [comment]
input length is changed to 64 chars in new version.
