### ISSUE TITLE
Why my nodemcu reboot when refresf the page during a measurement (bug or normal?) : 

### ISSUE THREAD

**Issue by MagTun** [opendata-stuttgart/sensors-software#340]
I am not sure if this is the real cause, but when I refresh the page http://IP/values  by pressing F5 just when a measure is done, then the nodemcu bugs and it reboot itself

Step to reproduce: 

1. open http://_the_local_IP/values 
2. wait until you see 143 seconds since last measurement.
3. press several times per second `F5`(just to be sure to press on time)
4. if you see the next measurement update, continue to press  `F5` a couple of more times

At this point, the browser returns the error `can't connect`. If I wait for several seconds (maybe a minute) then I see the page without any measure and with the red warning "Still 143 seconds until first measurement."

I am using chrome. 

Is it normal?

**Comment by ricki-z** [comment]
The NodeMCU has 80kByte of RAM. Could you please keep this in mind if you "try to test something ...". For each page call the resulting page has to be build in RAM. With a size of 2kByte per page and an available RAM of 30 kByte you can calculate the moment when the NodeMCU is crashing.
Question: who is clicking reload again and again and again without waiting between the reloads? Could you please write issues for real world problems.

**Comment by MagTun** [comment]
Sorry I didnt' describe the problem the right way. The bug happened several times when I pressed F5 just once, just at the wrong time. 

But because I don't know the exact moment when one has to press one time F5 for the bug to appears, I wrote in the "step to reproduce" to press it several times.

**Comment by imaluschi** [comment]
I'm using NRZ-2018-123B and have no problems with rebooting while updating the website during measurements.
Pressed F5 in Firefox beginning from 140s since the last measurement as fast as i could - no crash.

**Comment by dirkmueller** [comment]
also can not reproduce with current firmware. maybe this can be closed? @MagTun ?

**Comment by MagTun** [comment]
Me too I can't reproduce this! Thanks for testing!
