### ISSUE TITLE
Better feedback about connected sensors in web interface

### ISSUE THREAD

**Issue by bertrik** [opendata-stuttgart/sensors-software#344]
We recently organised a luftdaten sensor workshop and one of the practical things I ran into is getting quick feedback about the sensors being  connected correctly or not.

It's easy to mix up some wires and have a not-functioning sensor, e.g. get the tx and rx wires switched on the SDS011 or get SDA/SCL switched on an i2c-humidity sensor. I think it would be convenient to quickly get feedback about whether the sensor was detected or not. The built-in website starts measurement only after the measurement interval of default 145 seconds. That means you'll just have to wait until you see a measurement, then perhaps adjust wiring and wait another few minutes to get feedback. I think the serial console already shows it, perhaps we can add it to the website too.

I see two solutions to this:
1) do a measurement cycle immediately after starting up and then wait, instead of first waiting and then doing the measurement
2) show the operational status of the sensors on the built-in web site. For example, just showing whether it was detected or not, or perhaps show the id of the sensor, would help a lot. 

I think I can play around a bit with this, perhaps post a pull request with this functionality in a few days.

**Comment by ropeters68** [comment]
Good idea! I noticed that in certain cases the blue light on the esp keeps blinking every few seconds if something is wrong.

**Comment by ricki-z** [comment]
Two points to remember when you change the source code:
1. Use the beta branch for pull requests
2. compiled binary may not be more the 512 kByte, otherwise OTA won't work
