### ISSUE TITLE
NRZ-2018-123B: Nach kurzer Zeit nicht mehr erreichbar

### ISSUE THREAD

**Issue by capitaenz** [opendata-stuttgart/sensors-software#350]
Hallo zusammen,

heute funktioniert mein Sensor nicht mehr. Zeitüberschreitung und die Seite kann erst nach einem Neustart (Stromlos machen) wieder aufgerufen werden. Habe gelesen, dass die CPU-Frequenz auf 160Mhz angehoben wurde. Vielleicht ist dies das Problem? Läuft der Sensor tatsächlich erst mit der NRZ-2018-123B auf 160Mhz? Gibt es eine Möglichkeit wieder 80Mhz einzustellen? 
Der Sensor ist auf dem Dach und außer einem Neustart kann ich nicht viel durchführen :-/

VG
Leif

**Comment by thymjan** [comment]
Mein Feinstaubsensor funktioniert seit 20.30 Uhr auch nicht mehr richtig. Der Access-Point wird aufgebaut, mit dem lokalen WLAN verbindet er sich nicht mehr. Habe ihn schon mehrmals neu gestartet, jedoch ohne Erfolg. Firmware NRZ-2018-123B.

**Comment by ricki-z** [comment]
Some of the sensors seems to behave in a 'strange' way. The soft reset after the installation of a new firmware issue seems not enough. Those sensors need a hard reset (power off and on).

**Comment by ricki-z** [comment]
@thymjan Wenn du dich mit dem Sensor-Accesspoint verbindest, wird dein WLAN dann auf der Konfigurationsseite in der Liste erreichbarer WLANs angezeigt. Die Liste sollte ein paar Sekunden nach dem Aufruf der Seite eingeblendet werden.

**Comment by thymjan** [comment]
@ricki-z Ja, mein WLAN wurde angezeigt, jedoch komischerweise nur mit 12% (ist sonst wesentlich besser). Hab dann auch einen Hard-Reset gemacht und die Routerzeit auf 30 Sekunden verkürzt. Mittlerweile scheint er wieder zu funktionieren. Die Qualität vom WLAN wird jetzt wieder mit 38% angezeigt.

**Comment by ricki-z** [comment]
@thymian aktuell mit Regen und teilweise Schnee kann das WLAN-Signal an den Sensoren deutlich schwächer ankommen. Im ungünstigsten Fall sind sowohl Sensor als auch die Außenwand nass, da hilft dann manchmal nur warten. Das dürfte vor allem beim ersten Verbindungsaufbau nach einem Neustart eine Rolle spielen, wenn doch ein paar mehr Pakete übertragen werden müssen und dann wahrscheinlich ein Timeout kommt.

**Comment by georgroehl** [comment]
Thanks for the mention, but i think you wanted to mention @thymjan and not me, @thymian. 
Have a great day everyone!

**Comment by capitaenz** [comment]
Nachdem ich den Sensor mehrmals stromlos gemacht habe, funktioniert dieser wieder.
Ich werde jetzt die Updatefunktion mit der nächsten nicht Beta deaktivieren, da der Sensor auf dem Dach ist und ich dort nicht ständig dran kann.
Die Verbindungsqualität ist unverändert wie immer: 
WiFi | Signal | -75 dBm
WiFi | Qualität | 50 %

VG
Leif

**Comment by robertprice** [comment]
I've found my sensor now fails to connect to my WiFi since the automatic upgrade, and instead drops into provisioning mode. It can see my network and has remembered the password, it just doesn't connect to it now.

**Comment by dirkmueller** [comment]
is this still an issue with NRZ-2019-125 ?

**Comment by dirkmueller** [comment]
Please reopen and let us know if there's still an issue. Thanks!
