### ISSUE TITLE
Configuration network requires password

### ISSUE THREAD

**Issue by mrgames13** [opendata-stuttgart/sensors-software#353]
Hi,
I've got a problem with two of my sensors. The configuration wifi is suddenly password protected although I didn't configured that this way. I hope you can help me.

**Comment by ricki-z** [comment]
you could follow the instructions for deleting the configuration by flashing an empty file system. Link to instructions: https://github.com/opendata-stuttgart/meta/wiki/Firmware-einspielen#l%C3%B6schen-der-konfiguration

**Comment by mrgames13** [comment]
Thank you for your quick and helpful answer. I got it working with variant 2.
Regards and happy new year!
