### ISSUE TITLE
A logger script for the SDS011 - swapped values for pm2.5 and 10?

### ISSUE THREAD

**Issue by KAlexK** [opendata-stuttgart/sensors-software#361]
Hi!
**sds011logger.py**
In code:
`return (pm10 , pm25)`
but assignment is:
`pm25,pm10=sdslog.read()`
Is it correct to swap values? As this:
`pm10,pm25=sdslog.read()`

**Comment by dirkmueller** [comment]
this has been fixed in 25d34a1607a1dcb9988c7d7b04293f09370e1695 - agree to close?
