### ISSUE TITLE
Not able to configure custom API (anymore)?

### ISSUE THREAD

**Issue by michalskop** [opendata-stuttgart/sensors-software#366]
Is it (still) possible to config local or custom API for the data?

The is just this page with no options for that (and "Back to home page" returns to the same page)

![image](https://user-images.githubusercontent.com/930251/51096796-9820f580-17bf-11e9-8cd1-17efa8f978ce.png)

**Comment by ropeters68** [comment]
The screenshot looks like the initial page to set-up the Wi-Fi connection. After save/restart you can logon again using the IP-address provided by your router, then you'll get the full configutation screen (including the API-option).

**Comment by michalskop** [comment]
Thanx @ropeters68!
I did not get it from the manual.

For future reference:
The settings of wifi (the first time or after a change of wifi/router) is at 192.168.4.1 (it is available when the board cannot connect to the internet).

However, the settings of the sensors, APIs, etc. is at the address given by the router if it is connected, e.g. 192.168.1.11 (one can get the address from the router admin pages, which may be at 192.168.1.1)
