### ISSUE TITLE
Not clear that auto update must be on to change the language.

### ISSUE THREAD

**Issue by DeeKey** [opendata-stuttgart/sensors-software#377]
Language change requires to download a new firmware.
This is only possible with "auto update" option ON.
It is not clear from UI.
Can the following note be added to the language change feature: "Turn auto update ON!"

https://github.com/opendata-stuttgart/sensors-software/issues/254

**Comment by dirkmueller** [comment]
The alternative is that we do an "autoupdate" if the language has been changed from the currently configured ones. that seems to be more seamless imho (but it will change the version to the latest one)

**Comment by DeeKey** [comment]
Lets close this issue! 
Problem solved!

**Comment by dirkmueller** [comment]
Nothing has been done yet, I still want to make this more obvious as many are falling into this trap.

**Comment by dirkmueller** [comment]
Has been fixed in -B7 now, closing.

**Comment by DeeKey** [comment]
Yes - now it can be close as it is absolutely clear that autoupdate is required to change the language!
