### ISSUE TITLE
Grafik: Verschaltung Sensor SDS011

### ISSUE THREAD

**Issue by polygontwist** [opendata-stuttgart/sensors-software#38]
Hallo, im Wiring-pdf ist VUSB mit 2,5µ statt 5V vom Feinstaubsensor (SDS011) verbunden - ist das korrekt? In der Textlichen Beschreibung ist er hingegen auf 5V gelegt und der 2,5µ nicht benutzt (halte ich für richtiger)!
(https://github.com/opendata-stuttgart/sensors-software/tree/master/esp8266-arduino/ppd42ns-wificonfig-ppd-sds-dht)

**Comment by ricki-z** [comment]
Das ist richtig. Es sollte auf den 5V-Pin gehen. Martin, kannst du das korrigieren?

**Comment by Marwe** [comment]
Asked ET to provide update from source

**Comment by rabede** [comment]
RXD und TXD sind ebenfalls vertauscht!

// SoftSerial RX PIN is D1 and goes to SDS TX
// SoftSerial TX PIN is D2 and goes to SDS RX

**Comment by Marwe** [comment]
Changed PDF (with LO)
