### ISSUE TITLE
NRZ-2018-123B: BME280 keine Daten mehr nach x Stunden 

### ISSUE THREAD

**Issue by brandungskieker** [opendata-stuttgart/sensors-software#386]
Verwende das Standard-Setup 
SDS011
BME280
mit Firmware NRZ-2018-123B

Vielleicht hat jemand einen Rat: In unregelmäßigen Abständen stoppt der BME280 Sensor bei mir die Übermittlung der Daten. Teilweise werden auch verkehrte Daten geschrieben. 
Im "Aktuelle Werte" Screen erscheint ein "-" bei den Werten. Ein Hard- oder Softreset hilft, danach werden wieder Daten gesendet. Die Regelmäßigkeit der "Sensor hang-ups" sieht man gut auf den Sensorgraphen:
https://www.madavi.de/sensor/graph.php?sensor=esp8266-830217-bme280

![](https://www.madavi.de/sensor/images/sensor-esp8266-830217-bme280-1-week.png)

**Comment by ghoeffner** [comment]
Evtl. related zu #384? :)

**Comment by muesli** [comment]
Kann ich hier auch feststellen.

**Comment by ricki-z** [comment]
@brandungskieker aktuell scheint der BME280 keine Aussetzer oder falschen Werte zu haben. Sehe ich das richtig? Wurde etwas geändert? Wäre interessant für die Leute mit dem gleichen Problem.

**Comment by brandungskieker** [comment]
@ricki-z es hat sich wieder beruhigt, habe am Sensor nichts verändert. Die Software ist meines Wissens die gleiche geblieben, oder gab es jüngst Updates?

**Comment by ricki-z** [comment]
Das letzte Update war im Dezember, die meisten Sensoren sollten das auch zeitnah erhalten haben.

**Comment by dokape** [comment]
Mit dem BME280 und der FW -123b läuft mein Sensor seit Wochen problemlos.
Vielleicht ein temporäres Kontaktproblem? Feuchtigkeit? Wackelkontakt? feine Erschütterungen?

**Comment by ricki-z** [comment]
@brandungskieker können wir den Issue schließen?

**Comment by brandungskieker** [comment]
Nicht auszuschließen dass es auch mit einem Defekt des Sensors zusammenhängt.
