### ISSUE TITLE
How to add new localisation?

### ISSUE THREAD

**Issue by stealth-ultd** [opendata-stuttgart/sensors-software#387]
What is the procedure of adding a localisation (new language) to the firmware? From what I can see, the intl_template.h needs to get translated. Is there anything more to be done, and where is this file to be uploaded to get included in a new release?

**Comment by ricki-z** [comment]
Copy the int_template.h, rename the copy to i.e. intl_gr.h for Greek (2-letter ISO country code). Translate the texts in this file. Then upload this file to the beta branch here or send it to me by mail. The translation will then be included in the next release.

**Comment by stealth-ultd** [comment]
Thanks - all clear!

**Comment by ricki-z** [comment]
@stealth-ultd can we close this issue?

**Comment by stealth-ultd** [comment]
sure!
