### ISSUE TITLE
Versionsunklarheit

### ISSUE THREAD

**Issue by polygontwist** [opendata-stuttgart/sensors-software#39]
Hallo,
ich hab Version #define SOFTWARE_VERSION "NRZ-2016-048"
in der readme steht was von:

> Bis Version NRZ-2016-15:
> DHT https://github.com/adafruit/DHT-sensor-library
> (DHT.cpp und DHT.h downloaden und in das Softwareverzeichnis kopieren) 
 ist damit die "NRZ-2016-015" gemeint? (die dht brauchte ich jedenfalls nicht)

**Comment by ricki-z** [comment]
Ich glaube, da steht: bis Version NRZ-2016-15.
Ich verstehe die Frage nicht. Wenn wir aktuell die Version NRZ-2016-048 haben, braucht man laut diesem Abschnitt die beiden Dateien nicht.

**Comment by polygontwist** [comment]
ja die 0 ist dort irritierend...
