### ISSUE TITLE
Lokale JSON API

### ISSUE THREAD

**Issue by muesli** [opendata-stuttgart/sensors-software#393]
Bietet die Firmware auch eine lokale JSON API an?

**Comment by ricki-z** [comment]
Unter http://<ip-addresse-des-sensors-in lokalen-netz>/data.json können die Daten abgerufen werden. Zu beachten ist, das wir den lokalen Webserver während des Sendens an die Server deaktivieren, da sonst der Speicher knapp wird. Die Datei ist also alle 2,5 Minuten kurzzeitig nicht erreichbar.
Falls der Issue damit erledigt ist, bitte schließen.

**Comment by muesli** [comment]
Das wirft mir nur ein 404 not found zurueck.

**Comment by ricki-z** [comment]
Sorry github hat einen Teil der Adresse "geschluck". Dort sollte stehen http://{ip-adresse-des-sensors-im-lokalen-netz}/data.json

**Comment by muesli** [comment]
Keine Sorge, hatte ich schon richtig verstanden :-) Dennoch: 404 not found.

**Comment by ricki-z** [comment]
Was komisch ist, weil es bei meinem Sensor mit der aktuellen Firmware funktioniert.
Was passiert bei http://{ip-adresse-des-sensors-im-lokalen-netz}/ ?

**Comment by muesli** [comment]
Ich erhalte das Admin/Config Interface, um meine Adresse & Geodaten sowie Sensortyp und ID des SDS011 einzustellen.

**Comment by ricki-z** [comment]
Dann läuft auf diesem Sensor NICHT unsere Firmware. Hier ist also das falsche Repo für deine Frage. Bitte wende dich an die Entwickler der Firmware, die auf deinem Gerät läuft.

**Comment by muesli** [comment]
Huch?! Vielen Dank fuer die Info.

**Comment by ricki-z** [comment]
Interessant wäre aber, welche Firmware da läuft. Bzw. von wem die ist?

**Comment by muesli** [comment]
Das frage ich mich nun auch. Die Firmware wurde beim smartair Workshop in Augsburg zur Verfuegung gestellt. Mir wurde gesagt, es handelt sich um dieses Repo hier, genauer gesagt:

https://github.com/opendata-stuttgart/sensors-software/tree/master/airrohr-firmware

**Comment by ricki-z** [comment]
Wir fragen aber weder die Adresse oder Geo-Daten ab noch die ID des SDS011 (diese können wir über die Software auslesen). Von daher kann es einfach nicht unsere Firmware sein.
Kannst du mir einen Screenshot schicken (rajko(at)codefor.de)?

**Comment by muesli** [comment]
Klar, kein Problem:

![image](https://user-images.githubusercontent.com/146378/54478276-9fd93680-4810-11e9-83ce-ae04e27bbf0a.png)

Firmware Binary stammt scheinbar von hier: http://www.teco.edu/research/mitmachen-im-smart-air-quality-network-workshop-augsburg/ (CrowdSensor v0.8)

Ich hoffe du kannst etwas Licht ins Dunkel bringen, ich bin endgueltig verwirrt :confused:

**Comment by ricki-z** [comment]
Würde mich ja mal interessieren, wiele Leute bei dem Workshop waren und wieviele davon eigentlich einen Sensor für Luftdaten.info bauen wollten.
Denn der dort gebaute Sensor sendet vielleicht auch an uns, aber ohne Registrierung ist der auf unserer Karte nicht zu sehen. Und zum anderen sendet er an einen Server am KIT. Die dort ankommenden Daten werden aber aktuell gar nicht veröffentlicht. Das macht dann X Bausätze, die still und leise vor sich hin messen. Das Projekt des KIT findest du unter http://www.smartaq.net/STARTSEITE/

**Comment by muesli** [comment]
@ricki-z Danke, das klaert auch gleich eine weitere Frage, die ich hatte: wieso ich mich auf luftdaten.info separat registrieren muss :wink:

Mal sehn, vielleicht tausche ich dann einfach selbst die Firmware.

Am Workshop haben ca. 30 Leute teilgenommen. Ich moechte betonen, dass es auch gut moeglich ist, dass ich schlichtweg etwas falsch verstanden habe. Die schriftliche Anleitung spricht tatsaechlich auch nur von einem "Sensor nach dem Vorbild von luftdaten.info", verlinkt aber auch dorthin und zu euren Seiten.

**Comment by ricki-z** [comment]
Andere Firmware wird schwierig, weil da ein ESP32 eingesetzt wird. Aber vielleicht bekommen wir das auch so hin. Siehst du auf der Seite irgend eine Art Seriennummer (außer der des SDS011)?

**Comment by muesli** [comment]
Spielst du jetzt auf die separate luftdaten.info Registrierung an? Wenn ja, dann hab ich das bereits gemacht, warte allerdings immer noch darauf, dass mein Sensor hinzugefuegt wird. Ich kann dir die Sensor ID aber gern nochmal per Mail schicken!

**Comment by ricki-z** [comment]
Ja, schicke mir die Sensor ID bitte noch einmal per Mail. Ich sehe hier leider EMail-Adresse nicht und habe dadurch nichts, wonach ich suchen könnte.
