### ISSUE TITLE
Proxy config in AP Mode

### ISSUE THREAD

**Issue by rohit-rcrohit7** [opendata-stuttgart/sensors-software#398]
Hi,

The Nodemcu which starts in station mode (AP) to connect to an available WiFi needs your help. The WiFi here in question is behind a firewall and needs a proxy server and port to be provided for authentication. My Nodemcu connects to the WiFi and gets an IP address but as expected can't send the the data over to the madavi server. Is there a way to configure proxy details? ( It's a school WiFi where am trying to monitor air pollution)

Thanks!

**Comment by ricki-z** [comment]
In the actual version it's not possible to configure a proxy. And it's also not planned. We are running out of available flash memory. So we can't implement all features.
May be it's possible to set the sensor on something like an exception list?

**Comment by rohit-rcrohit7** [comment]
Ahh I imagine, 4MB is not a lot to work with. You are right, quiite possibly, that would be the way out. ( If we manage to track down the IT guy to do so).  Thanks!
