### ISSUE TITLE
Compile with 80Mhz or 160Mhz

### ISSUE THREAD

**Issue by GitOffMyGrass** [opendata-stuttgart/sensors-software#399]
The readme.md says to compile the airrohr-firmware sketch with setting for CPU frequency of 80Mhz.  The release notes for latest release ( NRZ-2018-123B) say  "set CPUFreqency to 160MHz (for faster TLS handling)."  This may be a dumb question but does that mean we should be compiling the sketch with CPU frequency of 160MHz or should it be with 80MHz per the readme?

**Comment by ricki-z** [comment]
The source needs to be compiled with 160MHz. I will update the Readme.
