### ISSUE TITLE
fehlt Installationshinweis Adafruit_BME280_Library

### ISSUE THREAD

**Issue by polygontwist** [opendata-stuttgart/sensors-software#40]
ist auch bei der Installation von nöten (sorry hab die readme editiert)

**Comment by ricki-z** [comment]
Ich hoffe, nicht direkt auf Github.

**Comment by polygontwist** [comment]
doch :-/

**Comment by ricki-z** [comment]
Die BME Unterstützung gibt es seit letztem Freitag und ist noch Beta.
Die Readme wird nicht jedesmal durchgeschaut, wenn ich eine neue Version hochlade. Da würde ich gerade mehr Readme als Sourcecode editieren. Ich sammle das, aktualisiere die Bibliotheken, schaue, ob das Kompilieren durchläuft, und schreibe dann die aktuellen Lib-Versionen dazu.

**Comment by polygontwist** [comment]
aha, dann war es eine ungünstiges zusammentreffen, als ich das Projekt kopiert habe. danke.
