### ISSUE TITLE
No sensor readings from SDS011

### ISSUE THREAD

**Issue by andreas-bulling** [opendata-stuttgart/sensors-software#404]
Hi,

I've just put together an air quality sensor from source (Firmware: NRZ-2018-123B). Platform is a WEMOS D1 ESP8266.

DHT11 works fine but I can't get any sensor readings from the SDS011. I've connected it as described (TX -> D1, RX -> D2), the fan is running, and this [Python script](https://github.com/aqicn/sds-sensor-reader/blob/master/sds-reader.py) also shows values for PM2.5 and PM10 when connecting the sensor directly to the PC via USB.

However, I am not able to get any sensor readings on the luftdaten.info WEMOS D1 device. Debug Info High doesn't show anything useful.

Any ideas/suggestions for how to debug this?

**Comment by DmitrSou** [comment]
Stupid suggestion - do you mark the sensor in config?

**Comment by ricki-z** [comment]
Is it possible that the sensor was reconfigured before with another software? The sensor needs to be set to continuous mode, not passive mode. And some test scripts change this to passive more.

**Comment by andreas-bulling** [comment]
> Is it possible that the sensor was reconfigured before with another software? The sensor needs to be set to continuous mode, not passive mode. And some test scripts change this to passive more.

Possible but unlikely - I only plugged it into the USB port or connected it to the D1 so far. The simple Python script does no configuration at all - it's just a simple serial connection, in contrast to the firmware - not sure why..

**Comment by andreas-bulling** [comment]
> Stupid suggestion - do you mark the sensor in config?

yes

> If so - I would double check RX/TX connection...

I did - including swapping the cables... :(

**Comment by DmitrSou** [comment]
Is there possible to read diagnistic output via serial? If so I would change log level to Debug and see what happens. Actually I've never have deal with WEMOS D1 device...

**Comment by andreas-bulling** [comment]
I tried many combinations and finally found a working setup:
D1 -> RX (pin 2 SDS)
D2 -> TX (pin 1 SDS)

Then, in ext_def.h, I set
```
#if defined(ESP8266)
#define GPS_SERIAL_RX D5
#define GPS_SERIAL_TX D6
#endif
```
