### ISSUE TITLE
DS18B20 wird nicht angezeigt.

### ISSUE THREAD

**Issue by gerald-b** [opendata-stuttgart/sensors-software#409]
Hi,

ich verwende die Firmware: **NRZ-2018-123B**
Angeschlossen habe ich "nur"
* OLED SSD1306
* BME280 
* DS18B20

Leider wird mir am OLED Display der DS18B20 nicht angezeigt.
mit dem BME280 passt alles.
Ich habe auch nach dem Anschließen des DS18B20 nochmal das Display "rauskonfiguriert" und anschließend wieder hinzugefügt. Leider ohne Erfolg.
Auch das data.json ist vollständig mit beiden Sensoren

![image](https://user-images.githubusercontent.com/15955282/57647802-37b29100-75c4-11e9-8bf1-51429bf4331b.png)

Was ist die Idee:
Ich möchte den Wasserdichten Sensor (DS18B20) in ein Aquarium hängen.
Der BME280 soll die Temperatur im Zimmer erfassen.
Beide Werte möchte ich am Display ablesen können.

**Comment by ricki-z** [comment]
Das liegt jetzt auch als Anwendung etwas neben dem eigentlichen Zweck der Firmware.
Wir zeigen auf dem Display nur den Wert des jeweils "besten" Sensors an. Wenn also z.B. ein DHT22 und ein BME280 verbaut wären, würden die Werte des BME280 angezeigt. Bei einem DHT22 und einem BMP280 (also ohne Luftfeuchte) würde die Temperatur des BMP280, die Luftfeuchte des DHT22 unf der Luftdruck des BMP280 angezeigt.

**Comment by gerald-b** [comment]
OK. Danke.
