### ISSUE TITLE
airrohr-firmware NRZ 2018-124-B2  - compile error JSON

### ISSUE THREAD

**Issue by FrankUlbrich** [opendata-stuttgart/sensors-software#410]
Hallo,
ich passe für mich die airrohr-firmware gerade für einen WEMOS D1 mini pro an.
Das compilen der Version NRZ 2018-123-B  funktioniert fehlerfrei.
Das compilen der Version NRZ 2018-124-B2 wirrft einen Fehler im Sourcecode 

![2019-05-19_13h12_27](https://user-images.githubusercontent.com/50796924/57981598-adda4c00-7a39-11e9-81ca-77e2864a7495.png)

Comiled wird mit ARDUINO 1.8.3

Tolles Projekt, habe es zufällig gefunden. Baue an einem Sensor für mich und einen für eine Pfadfindergruppe. 
Danke für die Initiative.
Frank

**Comment by ricki-z** [comment]
Hallo,
leider hat die 6er Version der ArduinoJSON Bibliothek einige inkompatible Änderungen. Für die neueste (Beta-)Firmware-Version muss deshalb die Version 6 installiert sein, während für die aktuelle Release Version noch die 5er Version installiert sein muss.

**Comment by FrankUlbrich** [comment]
Danke für die Info und vielen Dank für Softwareentwicklung.
