### ISSUE TITLE
Duel Particle  sensors

### ISSUE THREAD

**Issue by jordanc365** [opendata-stuttgart/sensors-software#419]
Hello,
Is it possible to equip the platform with 2 dust sensors instead of a temp/ humidity sensor?
It could be helpful as one could see that one of the sensors are degrading if they report different values.
Here's an example of a sensor that does this: 
[https://www2.purpleair.com/products/purpleair-pa-ii-sd](url)

**Comment by ricki-z** [comment]
This would be a very instable setup as the NodeMCU isn't really fast enough to simulate 2 serial interfaces at the same time. And there is no hardware serial which we could use.

**Comment by Adorfer** [comment]
for dual RS232 it would be at least neccesary to pass from ESP8266 to the more powerfull ESP32 (which is essential at least 3€ more expensive)

**Comment by jordanc365** [comment]
Thanks for the help! I'll have a look into it
