### ISSUE TITLE
wire: 'void TwoWire::pins(int, int)' is deprecated

### ISSUE THREAD

**Issue by polygontwist** [opendata-stuttgart/sensors-software#42]
in der "ppd42ns-wificonfig-ppd-sds-dht.ino" wird diese Zeile (1898) angemosert. 
```
#if defined(ESP8266)
	Wire.pins(D3,D4);					// must be set before all other I2C cmds
```
Soweit meine Recherche ist ein Wire.pins(D3,D4); nicht mehr nötig, das macht ja das `Wire.begin(D3,D4);` was dahinter kommt.
Wenn ich es auskommentiere compiliert es ohne Meldungen.

**Comment by michael-k** [comment]
Can you send a PR?

**Comment by ricki-z** [comment]
Wire.pins(D3,D4); removed in last version
