### ISSUE TITLE
Add information to field lengths and correct current field lengths

### ISSUE THREAD

**Issue by ss89** [opendata-stuttgart/sensors-software#433]
A friend of mine bought some sensors and uses it with this firmware.
I did setup some influxdb for him to use, ofcourse with the maximum length i thought possible for this firmware, which looked like it would be 50 characters.
Since this is the maxlength in the user interface.
However it seems that due to null termination you can only use 49 characters(?).

Feature request:
* Please add the length of the fields in brackets next to the fields label
* Please fix the max-length attribute in the html so that it reflects the real maximum

**Comment by ricki-z** [comment]
The fields host and path for the InfluxDB config are limited to 100 byte (minus 1 for null termination). This should be enougth for most cases. The fields should be saved as 1 byte per character. If you use Unicode chars the useable length is only 50 chars.

**Comment by ss89** [comment]
It seems that i looked at a fork or so. 
Never the less, the interesting parts username and password are 65 bytes in size.
Or my friend used an outdated version with lower field lengths?
Still wondering why it did only work with a lower length for the password field.

**Comment by JDTm** [comment]
Installed Firmware: NRZ-2018-123B

**Comment by dirkmueller** [comment]
The max-length attribute has been fixed already in the beta branch. I can add the max input length as an hover overlay, however showing it always looks far too intrusive for such a (relatively unimportant) piece of information.

**Comment by dirkmueller** [comment]
This has been implemented in beta branch. Please don't hesitate to reopen if there is still an issue remaining.
