### ISSUE TITLE
HTTP Header umbenennen

### ISSUE THREAD

**Issue by corny** [opendata-stuttgart/sensors-software#53]
`Pin` und `Sensor` sind keine standardisierten HTTP-Header. Sie sollte daher umbenannt werden in `X-Pin` und `X-Sensor`. Wofür wird der Pin-Wert überhaupt verwendet?

**Comment by ricki-z** [comment]
Dafür müssten wir den API-Server anpassen. Dieser erwartet den Pin-Header, um die Werte einem Sensortyp zuordnen zu können. Zudem existieren inzwischen zahlreiche API-Clients, welche diese Header nutzen und nicht so ohne weiteres geupdated werden können. Wir müssten also auf lange Zeit die API jeweils 2 Varianten auswerten lassen.

**Comment by corny** [comment]
Ok, verstanden.

**Comment by ricki-z** [comment]
Ich habe mir gerade

**Comment by ricki-z** [comment]
Ich habe mir den Code für die Header-Auswertung gerade nochmal angesehen. Ich werde den so umbauen, das beide Varianten (also mit und ohne 'X-') möglich sind. Damit können dann die 'alten' Clients weiterhin ihre Daten schicken.

**Comment by corny** [comment]
Sehr schön!

**Comment by ricki-z** [comment]
Ist geändert, schau mal auf die aktuelle Version.

**Comment by corny** [comment]
Sieht gut aus :+1:
