### ISSUE TITLE
Firmware: NRZ-2019-126-B2 BME280 keine Luftfeuchtigkeitsmessung

### ISSUE THREAD

**Issue by BudBundi** [opendata-stuttgart/sensors-software#533]
Mit der Firmware: NRZ-2019-126-B2 ist die gemessene Luftfeuchtigkeit dauerhaft auf 0%
Powercycling brachte keine Änderung.

**Comment by dirkmueller** [comment]
Stimmt, mit der non-beta firmware gehts, aber es scheint nur bei aussensensoren (hohen luftfeuchtewerten) aufzutreten, innen gehts. ich schaue..

**Comment by dirkmueller** [comment]
Ich denke #535 loest das problem, muss dann nachher mal mit dem laptop rauslaufen.. :-)

**Comment by dirkmueller** [comment]
Sollte nun gelöst sein.

**Comment by dirkmueller** [comment]
Problem ist in NRZ-2019-126-B3  gefixed!

**Comment by BudBundi** [comment]
Scheint geholfen zu haben, danke
