### ISSUE TITLE
Custom API Path input field very short

### ISSUE THREAD

**Issue by ubergesundheit** [opendata-stuttgart/sensors-software#55]
I am referring to this [line](https://github.com/opendata-stuttgart/sensors-software/blob/ea71f041ee2d66c8344248c00aa2193da90d5cbc/esp8266-arduino/ppd42ns-wificonfig-ppd-sds-dht/ppd42ns-wificonfig-ppd-sds-dht.ino#L893). Is there any reason the path is restricted to 50 characters?

**Comment by ricki-z** [comment]
We need to restrict the memory permanently used by vars. The NodeMCU has very limited RAM. Can you give me an example with a path greater than 50 chars?

**Comment by ubergesundheit** [comment]
Ok, fair point. I don't have an example, I was just curious. Thanks for clearing that up.
