### ISSUE TITLE
Missing voices in italian configuration page.

### ISSUE THREAD

**Issue by stewecar** [opendata-stuttgart/sensors-software#562]
Hello,
some of the "voices" in the sensor page are missing under 'configuration'.
For example 'load beta firmware' in italian is 'carica software beta' or flip display option is 'ruota il display di 180°"..are missing.
I could translate if you want and load in the beta branch.
s.

**Comment by ricki-z** [comment]
Hi @stewecar it would be nice if you could add the translation to the beta branch.

**Comment by stewecar** [comment]
sorry i am a newbie..should i modify the file in sensors-software/airrohr-firmware/intl_it.h or i have to upload a completely new one in the same directory? Thanks..

**Comment by dirkmueller** [comment]
Just update the file in place and send a PR. Or if you're unsure, just paste the translations that should be added as a comment here.

**Comment by stewecar** [comment]
thanks! i am updating it..

**Comment by stewecar** [comment]
done! thanks!

**Comment by dirkmueller** [comment]
@stewecar please change the pr to be submitted against the *beta* branch instead of *master*

**Comment by stewecar** [comment]
sorry..done now..

**Comment by stewecar** [comment]
there is a little change that i would like to make..i made a little error in a word..could i change it or is it a problem now? thanks!

**Comment by dirkmueller** [comment]
I merged the typo fix.. should be all in #565

**Comment by dirkmueller** [comment]
will be in 126-B7 or newer
