### ISSUE TITLE
maps. sensor.community & maps.luftdaten.info sites are down.

### ISSUE THREAD

**Issue by Petarkir2000** [opendata-stuttgart/sensors-software#592]
Hello, Do you know that the two sites do not work, including madavi.de?

**Comment by dirkmueller** [comment]
confirmed, accessing https://meine.luftdaten.info/sensors gives "internal server error"

**Comment by ricki-z** [comment]
Was a temporary issue. The hardware node running the virtual machine had a hardware problem.
