### ISSUE TITLE
NRZ-2019-128-B3-SDS011-fix-long-delay cannot change language.

### ISSUE THREAD

**Issue by Petarkir2000** [opendata-stuttgart/sensors-software#593]
@dirkmueller in addition to issue https://github.com/opendata-stuttgart/sensors-software/issues/581# . I found that with the version NRZ-2019-128-B3-SDS011-fix-long-delay I cannot change the language. When I flashed latest_bg.bin I cannot change it on English for example. I did a clear flash with erase before.

**Comment by dirkmueller** [comment]
Duplicate of https://github.com/opendata-stuttgart/sensors-software/issues/377
