### ISSUE TITLE
feature request: an option to rename the nodeMCU

### ISSUE THREAD

**Issue by WiliTest** [opendata-stuttgart/sensors-software#595]
I understand you try to limit the code, but if that's possible, it would be great to be able to set a custom name for the NodeMCU. I run several sensors, they appear as ESP_XXXXXX, which is quite confusing.
Thanks!

**Comment by dirkmueller** [comment]
where do you see ESP_XXXXXX (I guess XXXXXX is a number)?

**Comment by WiliTest** [comment]
I see them in the list of connected device of my router (that's how I check if they are all connected, and to get their IP)

**Comment by dirkmueller** [comment]
Ah, right, so that's likely the dhcp hostname. I will check this.

**Comment by dirkmueller** [comment]
Will be in the next beta release.
