### ISSUE TITLE
Button "Back to home page" is not needed on the main page

### ISSUE THREAD

**Issue by DeeKey** [opendata-stuttgart/sensors-software#603]
Button "Back to home page" is not needed on the main page as it leads back to the same home page :)

**Comment by ricki-z** [comment]
Excluding this on one page only would need some logic and with that more memory.

**Comment by DeeKey** [comment]
Ok, then lets put WontFix tag and close this issue.

**Comment by ricki-z** [comment]
Another question: Do you tell this every web site? Nearly every web site I know has the home button on the home page. (This is what templates do and what we also use to create the pages)
