### ISSUE TITLE
Capture serial output in a small ring buffer for web console

### ISSUE THREAD

**Issue by dirkmueller** [opendata-stuttgart/sensors-software#612]
For debugging sensors without having to carry laptops etc to difficult to reach (or cold :-(( ) locations it would be useful to have the last 512 bytes of serial output available in the /status webpage. 

probably we just need to create a small wrapper that overloads the virtual write() method and stores it (also) in a memory backed ring buffer.

**Comment by DeeKey** [comment]
It would be nice to automatically send crash reports Like Linux distros do.
But that will be the next step I guess...

**Comment by dirkmueller** [comment]
The serial debug mirroring has been implemented in a slightly hacky way. Will consider this issue done even though it will still need  a bit of polishing going forward.
