### ISSUE TITLE
airrohr-firmware fails to connect to wifi

### ISSUE THREAD

**Issue by Qwertie-** [opendata-stuttgart/sensors-software#615]
I have configured everything in the same way as [the manual](https://luftdaten.info/en/construction-manual/#komponenten-schaltung). After flashing the firmware I can get to the config page to enter the wifi details and then the page reloads and is blank. After that the device never connects to the wifi AP I just entered. Tried this a few times with the beta and non beta firmware a few times but had no luck.

**Comment by dirkmueller** [comment]
can you connect the node to  usb-serial debug https://github.com/opendata-stuttgart/sensors-software/blob/master/airrohr-firmware/Readme.md#debug-via-usb-serial and paste its output when it tries to connect to wifi?

**Comment by dirkmueller** [comment]
is there something special about your access point? note that this hardware requires 802.11n on 2.4Ghz to be allowed by the AP. 5Ghz (which is the modern default these days) does not work.

**Comment by Qwertie-** [comment]
I'll give that debug tool a test tonight. I don't think there is anything special about the setup. I attempted to connect to my rotuer 2.4ghz and a hotspot from my phone. The networks show up on the config page and I clicked on it to fill the network name.

**Comment by dirkmueller** [comment]
Thanks, that sounds promising. Other guess would have been that it uses one of the exotic wifi channels (channel 12+) and it for some reason refuses to use those.

**Comment by Qwertie-** [comment]
I'm seeing this on a loop
![Screenshot from 2020-01-04 11-11-54](https://user-images.githubusercontent.com/6601505/71964643-e8edf180-324d-11ea-8ddc-1473f7de0dde.png)

**Comment by Qwertie-** [comment]
I'm seeing this on a loop
![Screenshot from 2020-01-08 19-33-35](https://user-images.githubusercontent.com/6601505/71964679-fdca8500-324d-11ea-97c3-9032ae39f040.png)

**Comment by dirkmueller** [comment]
so this is NRZ-2019-124-B10. with other words you're one of the two that are still on this old version.. can you please flash the latest one, downloaded from here: 

https://firmware.sensor.community/airrohr/update/ (choose latest_XX.bin where XX is the locale you're interested in). 

using this command line:

```shell
esptool.py  --chip auto --port $dev --baud 460800 write_flash -fm dio 0x00000  latest_xx.bin
```

**Comment by Qwertie-** [comment]
```
Connecting to OpenWrt
...........
WiFi connected,
```

:+1: 

Any idea why https://github.com/opendata-stuttgart/airrohr-firmware-flasher/ includes an old version of the firmware?

**Comment by dirkmueller** [comment]
I've never used this software, but it seems it simply refers to the abandoned firmware server. we switched to sensor.community  a few months ago. 

https://github.com/opendata-stuttgart/airrohr-firmware-flasher/pull/23 should fix this.

**Comment by dirkmueller** [comment]
Thanks for the help troubleshooting this!
