### ISSUE TITLE
Custom sample rate

### ISSUE THREAD

**Issue by jo-me** [opendata-stuttgart/sensors-software#62]
Hi, 
where can I modify the firmware so that the sample rate is reduced to e.g. every 5min instead of every minute and thereby increasing the battery life?

Thanks
Jochen

**Comment by reibuehl** [comment]
The variables sending_intervall_ms defines one cycle. During that time, the sensor is on for warmup_time_SDS_ms + reading_time_SDS_ms.

**Comment by jo-me** [comment]
Thank you!
