### ISSUE TITLE
firmware update NRZ-2020-129 (Jan 7 2020 13:43:50)  HTML read problem

### ISSUE THREAD

**Issue by Rewop-jpc** [opendata-stuttgart/sensors-software#620]
After the firmware update NRZ-2020-129 (Jan 7 2020 13:43:50) I cannot read the  HTML  /values page  with VB.net to retrieve the values for my software.

**Comment by dirkmueller** [comment]
for machine readable version, /data.json should be used instead. 

what is the issue when you try reading it? can you access it manually? is there an error message that would give us a hint on what's going on?

**Comment by Rewop-jpc** [comment]
I use this with other html pages in VB.net. Until now it worked fine:

        Dim client As WebClient = New WebClient
        Dim data As Stream = client.OpenRead("http://192.168.1.125/values")
        Dim reader As StreamReader = New StreamReader(data)
        Dim str As String = ""
        Dim text As String = ""
        Do
            str = reader.ReadLine()
            text = text & str
        Loop Until str Is Nothing

After that I retrieve te values i want.

I have not used the json before?

**Comment by Rewop-jpc** [comment]
The 'text' is fully filled, but you can see only the first part. 
The real reason was:
Number of measures is removed from the value page

Solved

**Comment by dirkmueller** [comment]
Yes, this is now shown in /status instead. If you want I can move this value back to /values , I kinda didn't expect anyone already using it there because I just added it a few months ago. The idea was that /data.json and /values are now similar and sensor centric. Device centric data is now under /status.

**Comment by dirkmueller** [comment]
let me know if there is anything remaining.

**Comment by Rewop-jpc** [comment]
I see where it is now. I used it to see if the unit was recently reset/restarted.
