### ISSUE TITLE
Device is not working with hidden SSID on channel 11-13

### ISSUE THREAD

**Issue by DeeKey** [opendata-stuttgart/sensors-software#626]
Device is not working with hidden SSID on channel 11-13
To reproduce
1) Hide SSID and switch it to channel 11-13
2) Load and configure old stable version (125 or earlier)
3) Initiate update to stable

Expected:
1) After update sensor will reconnect to hidden WIFI

Actual:
1) Sensor is not able to connect to hidden WIFI with channel from 11-13
2) If you make SSID visible or change channel it will connect successfully

**Comment by DeeKey** [comment]
Seems that this is SDK problem according to @dirkmueller

**Comment by dirkmueller** [comment]
Fixed in NRZ-2020-130-B2 or newer (just subscribe to the beta channel)

**Comment by dirkmueller** [comment]
Reopen until landed in stable

**Comment by DeeKey** [comment]
Is it finally landed in stable?

**Comment by ricki-z** [comment]
@DeeKey should be in stable now, but I haven't tested it yet.
