### ISSUE TITLE
SPS30 connection issue

### ISSUE THREAD

**Issue by Petarkir2000** [opendata-stuttgart/sensors-software#630]
Hello,
I try to connect the sensor SPS030, but I fail. 
I connect the sensor to it in the same way as SD011, but unfortunately no data.
Could you please tell me where I am wrong?
Attaching photos.

![sps30_2](https://user-images.githubusercontent.com/37194471/72221971-3a58f200-3568-11ea-8374-94ad6124f563.jpg)
![SDS030-Scheme](https://user-images.githubusercontent.com/37194471/72221972-3a58f200-3568-11ea-81a0-794babf00dc0.jpg)
![SPS030-Configuration](https://user-images.githubusercontent.com/37194471/72221973-3a58f200-3568-11ea-96fe-d0e845d4b107.jpg)
![SPS030-Nodata](https://user-images.githubusercontent.com/37194471/72221974-3af18880-3568-11ea-98d5-ac671ff0436c.jpg)
![sps30_1](https://user-images.githubusercontent.com/37194471/72221975-3af18880-3568-11ea-8f16-aca5dd255057.jpg)

**Comment by stewecar** [comment]
Hello,
the SPS30 configuration is not the same as SDS011..

**SPS30 (I2C, 5V)**

Pinout: 1 2 3 4 5

    Pin 1 (5V) -> Pin VU/VIN
    Pin 2 (SDA) -> Pin D3 (GPIO0)
    Pin 3 (SCL) -> Pin D4 (GPIO2)
    Pin 4 (SEL) -> Pin GND
    Pin 5 (GND) -> Pin GND


**SDS011 (serial)**

Note: Serial connections are always crossed (RX on one side is connected with TX on other side)

    Pin 1 (TX) -> (RX) Pin D1 (GPIO5)
    Pin 2 (RX) -> (TX) Pin D2 (GPIO4)
    Pin 3 (GND) -> GND
    Pin 4 (2.5m) -> unused
    Pin 5 (5V) -> VU
    Pin 6 (1m) -> unused

**Comment by Petarkir2000** [comment]
Thank you!

**Comment by svenkubiak** [comment]
@Petarkir2000 
How did you end up wiring the SPS30 **and** the BMP/BME280? Afaik, the BMP/BME280 is also connected to D3/D4:
![image](https://user-images.githubusercontent.com/67564/165728511-042122e3-26e5-494f-a5bb-7c626d0792b7.png)

**Comment by pjgueno** [comment]
It is I2C. Same pins for both the buses.
