### ISSUE TITLE
Question - Android Mobile Feinstaub Source code?

### ISSUE THREAD

**Issue by CameronLamont** [opendata-stuttgart/sensors-software#632]
![image](https://user-images.githubusercontent.com/12403917/72302238-7ea9d680-36bd-11ea-8dc5-1aebdd132c41.png)

Hello I have been searching for the android source code to the app in the photo.  It directed me to this repo but the mobilefeinstaub directory doesn't appear to contain an android project.

The apk doesn't appear to read from my sds011 and wanted to try and get it working.

**Comment by ricki-z** [comment]
The "app" was developed with cordova (mentioned in the readme.md). Its some kind of webapp with access to hardware resources.
So it's not a native android app.

**Comment by CameronLamont** [comment]
OK thankyou, I couldn’t see mention of this app in the readme. I will look into Cordova to see if I can make use of that instead.

Sent from Mail for Windows 10

**Comment by ricki-z** [comment]
Cordova is not an app. It's an open-source mobile development framework.

**Comment by CameronLamont** [comment]
Understood, just haven’t used that framework before.  Thanks.

Sent from Mail for Windows 10

**Comment by dirkmueller** [comment]
@CameronLamont any question remaining?

**Comment by dirkmueller** [comment]
Please don't hesitate to reopen when there is something left..
