### ISSUE TITLE
wrong date

### ISSUE THREAD

**Issue by MacMarc** [opendata-stuttgart/sensors-software#637]
yesterday i noticed that the date is wrong. I'm writing the data via API to the data_simple.php and then read it out. the time is one hour behind.
example:

NTP Sync | 19
-- | --
NTP Info | 88.99.216.194 (0.pool.ntp.org) 
reachable:| Yes
Zeit | Sat Jan 18 15:54:18 2020

current time is 16:54.

firmware is:
`NRZ-2020-129
ST:1
SDK:2.2.2-dev(38a443e)
Core:2.6.2=20602000
lwIP:STABLE-2_1_2_RELEASE
glue:1.2-16-ge23a07e
BearSSL:89454af`

**Comment by dirkmueller** [comment]
* The time is not being embedded in the data that is sent to the APIs as far as I know. so the "system time" being "wrong" does not mean the API data is being submitted incorrectly

* The systems all run in UTC timezone, as there isn't a configuration option to set  the local timezone. the  sole purpose of running the node with NTP syncs is to ensure that we can properly validate HTTPS certificate expiration dates/times.
