### ISSUE TITLE
Sds011 will not write

### ISSUE THREAD

**Issue by wtrnl** [opendata-stuttgart/sensors-software#638]
The sds011 will not write the data.
Sometimes the data will displayed and some times not.
![Screenshot_20200118-171315_Chrome](https://user-images.githubusercontent.com/60041127/72666992-821fc380-3a17-11ea-8de9-e42ee2698c1f.jpg)
See also the graph.
![sensor-esp8266-6203772-sds011-25-day](https://user-images.githubusercontent.com/60041127/72666999-995eb100-3a17-11ea-8342-d5ac118a7e11.png)

**Comment by wtrnl** [comment]
I read the data every 5 minutes.
5 minutes data then 5 minutes no data

**Comment by dirkmueller** [comment]
@wtrnl please provide a screenshot of the "Device Status" (/status) page after a bit of uptime (20-50 measurements min) and if possible the serial output (with max info level set).

**Comment by wtrnl** [comment]
Hereby the printscreen.Serial output not possible.Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Dirk Mueller <notifications@github.com> Datum: 19-01-20  10:53  (GMT+01:00) Aan: opendata-stuttgart/sensors-software <sensors-software@noreply.github.com> Cc: wtrnl <info@weerstationtilburgreeshof.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [opendata-stuttgart/sensors-software] Sds011 will not write (#638) @wtrnl please provide a screenshot of the "Device Status" (/status) page after a bit of uptime (20-50 measurements min) and if possible the serial output (with max info level set).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opendata-stuttgart/sensors-software/issues/638?email_source=notifications\u0026email_token=AOKCPJYTSTGYJJG5O6UNA33Q6QPHRA5CNFSM4KIT3QQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKNX3I#issuecomment-575986669",
"url": "https://github.com/opendata-stuttgart/sensors-software/issues/638?email_source=notifications\u0026email_token=AOKCPJYTSTGYJJG5O6UNA33Q6QPHRA5CNFSM4KIT3QQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKNX3I#issuecomment-575986669",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dirkmueller** [comment]
@wtrnl unfortunately the mail attachment didn't come through.. please try attaching it on the webui of github (copy&paste in the browser)

**Comment by wtrnl** [comment]
![Screenshot_20200119-112058_Chrome](https://user-images.githubusercontent.com/60041127/72680866-f3668180-3abe-11ea-93f1-d3fdfb9ac92b.jpg)

**Comment by dirkmueller** [comment]
@wtrnl did you intentionally close this?

What can be seen is that one out of 131 measurement cycles failed to get data from sds011. 12 out of 131 failed to be able to send the data, the last time due to connection loss.

So this looks primarily like an issue with connectivity to the configured APIs.
