### ISSUE TITLE
Umrechnen von Partikel/Liter in µg/m³

### ISSUE THREAD

**Issue by f-breidenstein** [opendata-stuttgart/sensors-software#65]
Hi,

rein aus Interesse habe ich mir mal den billigeren PPD42NS Sensoren bestellt um die Werte mit denen eines Frenudes zu vergleichen der den teureren SDS011 hat. 

Aufgefallen ist, dass der SDS011 die Werte in µg/m³ angiebt, so wie es auch jede öffentliche Feinstaubmesstation macht. Der PPD42NS zeigt die Werte jedoch in #Partikel/Liter an. Damit kann man leider nicht wirklich was anfangen. Eine kurze Googlesuche hat gezeigt dass man die Werte eigentlich ineinander umrechnen kann.

Gibt es einen Grund wieso das aktuell in der Software nicht gemacht wird?  Weil in dieser Einheit sind die Werte halt ziemlich Nutzlos mMn.
Falls nein, würd ich mich die Tage mal hinsetzen und versuchen das reinzubauen und einen PR basteln.

Viele Grüße,
   Felix

**Comment by ricki-z** [comment]
Hallo Felix,
die Ergebnisse deiner Google-Suche würden mich ja interessieren. So einfach ist die Umrechnung der #Partikel/Liter in µg/m³ eben nicht. Lediglich er grobe Verlauf z.B. der gleitenden 24-Mittelwerte ist annähernd ähnlich. Daraus kann man zwar für einen spezifischen Standort einen Faktor bestimmen, dieser ist aber leider nicht allgemeingültig.
Und deshalb gibt es diese Umrechung nicht in unserer Software.
