### ISSUE TITLE
Request about pm's daily average

### ISSUE THREAD

**Issue by stewecar** [opendata-stuttgart/sensors-software#651]
Hello,
Is It possibile to implement the value "Daily average" about pm2,5 and 10 values?
Authorities release Daily average about pm values here in Europe and it would be nice to compare our datas with professional ones.
Many thanks!.
S.

**Comment by ricki-z** [comment]
Where should this be shown? On the map you can find the graph "24 h moving average". At midnight the "Daily average" is shown.

**Comment by stewecar** [comment]
Thanks, didn't notice It!
