### ISSUE TITLE
Blueberrye BME280 sensors pin layout

### ISSUE THREAD

**Issue by jpkrooney** [opendata-stuttgart/sensors-software#656]
Hi,
I bought a few Blueberrye BME280 sensors after seeing them suggested here: https://github.com/opendata-stuttgart/sensors-software/issues/137#issuecomment-331731434

However they arrived with no documentation and I have no idea of the pin layout - does anyone have this documented somewhere ?

**Comment by ricki-z** [comment]
You can find the needed informations in the FAQ at luftdaten.info ("Connect other sensors").

**Comment by jpkrooney** [comment]
No I could not find the answer there. I mean the pin layout of the cables from the sensor which are customised for this product.

After much, MUCH searching I found what I needed in a customer review of the Blueberrye BME280 on Amazon.de. Unfortunately I could not make a direct link to the photo but here is a screen shot for future reference

<img width="464" alt="BBE-BME280_pin_layout" src="https://user-images.githubusercontent.com/41968663/73383890-790ddc80-42ca-11ea-84b9-c8527f662ccf.png">
