### ISSUE TITLE
SPS30

### ISSUE THREAD

**Issue by pritt654321** [opendata-stuttgart/sensors-software#661]
Seit 02.02. bringt der SPS30 keine Werte mehr. Lief vorher ca. eine Woche stabil mit der Betasoftware auf dem NodeMCU. Seit 31.01 gibt es offensichtlich eine veränderte Beta, kann der der Grund sein?

**Comment by dirkmueller** [comment]
bitte poste doch ein screenshot der "http://airrohr-XXXXXX.local/status" website.

**Comment by dirkmueller** [comment]
also, does it recover after a power disconnect for 30s and powering it on?

**Comment by pritt654321** [comment]
hier einige Screenshots
![C81CA8F6-3E38-4A86-9EA9-B1808DE32016](https://user-images.githubusercontent.com/60623347/73777680-334d8a00-478a-11ea-88a3-dab913305b2e.jpeg)
![D259D3C5-9C4D-4A6A-8DB5-DDB81635D4AC](https://user-images.githubusercontent.com/60623347/73777682-334d8a00-478a-11ea-9e3d-8218aa4a9ff9.jpeg)
![3A1ED984-874A-4E86-93A3-0E83A512F603](https://user-images.githubusercontent.com/60623347/73777683-334d8a00-478a-11ea-9842-d9a26720fc1b.jpeg)

**Comment by pritt654321** [comment]
![F29AE0BE-921B-433D-82AD-20EA3622E523](https://user-images.githubusercontent.com/60623347/73778187-0f3e7880-478b-11ea-9f32-89dc6e937bcd.jpeg)

**Comment by dirkmueller** [comment]
Thanks. So the 'check wiring' means the sensor isn't even responding to the initialization..

**Comment by pritt654321** [comment]
Thanks Dirk, you were right,one of the resistors wasn‘t soldered proberly and i will reinstall everything on the weekend
