### ISSUE TITLE
Add Sensor ID to sensordatavalues for own API

### ISSUE THREAD

**Issue by gregorwolf** [opendata-stuttgart/sensors-software#67]
I think it would be a great addition to the JSON data that is sent in the sensordatavalues to provide also the Sensor ID. If you have multiple sensors you currently have to use URL Parameters or use different endpoints for the different sensors.

**Comment by darcoto** [comment]
You can find Sensor ID in HTTP Header of request. Look for X-Sensor

`POST /data.php  HTTP/1.1`
`Host: api.host.com`
`X-Sensor: esp8266-1335052`

**Comment by gregorwolf** [comment]
Good to know that the data is available in the HTTP header. But for the ease of consumption i.e. with Node-Red it would help to have it in the JSON directly.

**Comment by sethiele** [comment]
+1

**Comment by darcoto** [comment]
If @ricki-z confirm, I can add necessary code and make PR to project.
But in my opinion, this will add a few line of code witch will duplicate existing information (in header). As you may know, ESP has a limited memory and it is not a good idea to waste it.

**Comment by ricki-z** [comment]
I've added the ID to the JSON sent to custom api in the actual version. This will add 112 Byte to filesize. can someone test it?

**Comment by rexfue** [comment]
I've tested it. It doesn't work as is.
You send 'data' but should send 'data_4_custom'.
So change line 2573 to:
sendData(**data_4_custom**,0,host_custom,port_custom,url_custom,basic_auth_custom.c_str(),FPSTR(TXT_CONTENT_TYPE_JSON));

Then it works as expected .

**Comment by ricki-z** [comment]
Is changed. Will be pushed to the sensors in the next days.

**Comment by gregorwolf** [comment]
Excellent. Thank you all. Will check and then close the issue.

**Comment by gregorwolf** [comment]
Got Firmware: NRZ-2017-086 on my sensors now and the JSON does now contain esp8266id
