### ISSUE TITLE
Wrong data SDS011 ?

### ISSUE THREAD

**Issue by Rewop-jpc** [opendata-stuttgart/sensors-software#680]
The values in the graphs are very different from the values I retrieve from my sensor ?
Feinstaubsensor-11453096
https://www.sysanalyser.com/stofmap.html

**Comment by ricki-z** [comment]
There are some implementations for home assistant systems that use the same data to generate graphs. And until now we haven't heard about any problems.
So this may a problem on your side. But we can't tell much about this as this is a "black box" for us.

**Comment by Rewop-jpc** [comment]
I disconnected it for a while. After starting it up again, the graphs now looks much alike. Before your graph looked very unnaturally. Strait horizontal lines with a few spikes. Now it looks normal!

**Comment by ricki-z** [comment]
@Rewop-jpc so the issue is solved? Then please close it.
