### ISSUE TITLE
WPA3

### ISSUE THREAD

**Issue by Troubadix** [opendata-stuttgart/sensors-software#683]
Please add support for WPA3

**Comment by ricki-z** [comment]
This can only be added if it's supported by the Espressif SDK repo. And if it's available there then we will support this also. So please ask there for WPA3 support.

**Comment by dirkmueller** [comment]
Unfortunately it is very unlikely to happen, Espressif has feature-frozen the nonos-sdk that Arduino is relying on, and Arduino isn't even using the 3.0 release of NONOS_SDK that espressif is providing bugfix-maintenance for. Pointer to the documentation:

https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/README.md#support-policy-for-esp8266-nonos

Arduino still uses the 2.2.1 release, which is basically completely dead. 

WPA3 is only availble in the RTOS SDK: https://github.com/espressif/ESP8266_RTOS_SDK

a switch to RTOS will, if at all, only happen with arduino core 4.0, see https://github.com/esp8266/Arduino/issues/5790.

I hope you understand we close this for now, as there is little to be done here. we'll definitely add wpa3 once it becomes possible, or will have to switch to some other codebase or hardware basis as we do understand that over time 5Ghzs and WPA3 will become more important..
