### ISSUE TITLE
my sensor.php on localhost not received data from sensor

### ISSUE THREAD

**Issue by dejanBpetrovic** [opendata-stuttgart/sensors-software#692]
I can't receive any data from my sensor in my custom API. 
Here is my sensor configuration and down below is mu sensor.php code.
What is wrong?

![Screenshot_2020-03-16 Configuration](https://user-images.githubusercontent.com/18539504/76805282-b37dfb00-67de-11ea-88c5-c38418ddcacc.png)

`<?php

        $retVal = json_decode(file_get_contents('php://input'),true);
        $fp = fopen("C:/xampp/htdocs/MagarenceEvi/data.txt","a+");
        fputs($fp,"-----" . date("d.m.y H:i",time()) . "---\n");
        fputs ($fp,$retVal["esp8266id"] . "\n");
        fputs ($fp,$retVal["software_version"] . "\n");
        foreach ($retVal["sensordatavalues"] as $sensordatavalues) {
                $values[$sensordatavalues["value_type"]] = $sensordatavalues["value"];
        }
        $line = var_export($values,true);
        fputs($fp,$line);
        fclose($fp);

?>`

**Comment by ricki-z** [comment]
localhost is a "predefined" IP address (IPv4: 127.0.0.1, IPv6: ::1) and is bound to the local host. So if you use localhost as a hostname in the sensor configuration the sensor will send the data to itself (and not the target host). You need to use the IP address (or the hostname != locahost) of the system running your script.

**Comment by dejanBpetrovic** [comment]
Thank you ricki-z , this was a silly thing I did.
