### ISSUE TITLE
Korrekturfaktor für dnms Lärmmesser einstellen

### ISSUE THREAD

**Issue by atze09** [opendata-stuttgart/sensors-software#693]
Hallo,
Kann mir bitte jemand helfen wie ich den Korrekturwert des Lärmsensors bestmöglich einstellen kann. Ohne einen Abgleich mit einem anderen Mikrofon durchzuführen?
Danke.
Freundliche Grüße,
Dominik

**Comment by Franz4596** [comment]
hi atze09,  
ich habe Jan'20 ein DNMS (ICS43434 mit Teensy3.6) mit Schallpegelmessgerät verglichen, ab LAeq 42dBA ist keine Korrekrur notwendig (Abw.<1dB). Meines Wissens ist es nicht erforderlich das digitale Mikro zu kalibrieren (Korrekrur=0). Pegel unter 42 bis 37dBA haben deutliche Abweichungen, minimale Anzeige ist ~37dB:
![Vergleich](https://user-images.githubusercontent.com/62063765/77016795-07bce280-6979-11ea-92b4-33ad8806ab07.jpg)
mfg franz

**Comment by atze09** [comment]
Hallo Franz,
Vielen Dank für deine Arbeit. Das ist genau das was ich gesucht habe!
Freundliche Grüße,
Dominik
