### ISSUE TITLE
SDS sensor PM data not received when self flashing the NodeMCU

### ISSUE THREAD

**Issue by badea-andrei** [opendata-stuttgart/sensors-software#707]
I've flashed the sensor using the latest version of Arduino IDE (1.8.12) with the code on the master branch. When I first set up the sensor configuration via its wifi I've unchecked the auto update option and everything was working fine except the values from the sds sensor which we're not sending to my custom API. The temperature, humidity and wifi signal indicators were OK. So, to see if it's a problem with my hardware setup I've checked the auto update option and restarted the sensor. After the update was made the values were sending correctly to the API. I want to do some custom changes on the code and that's why I want to be able to self flash the nodeMCU. 

All the above steps were made without any changes to the code. Could this be from my Android IDE setup? The libraries? Even though I've installed all of the ones from the instructions.

**Comment by ricki-z** [comment]
The version in the master branch is exactly the version used for the actual stable firmware image.
So maybe there was a change in one of the libraries. Please check that exactly the lib versions are used that are mentioned in the platformio.ini.

**Comment by badea-andrei** [comment]
Got to the bottom of it.

It was [ESP8266 für Arduino](https://github.com/opendata-stuttgart/sensors-software/blob/master/airrohr-firmware/Contributing.md#build-using-arduino-ide) (Version 2.6.2). I had the newer version installed, 2.6.3.

Thanks for the hint.
