### ISSUE TITLE
open access point configuration page has WiFi password embedded

### ISSUE THREAD

**Issue by carstenjahn** [opendata-stuttgart/sensors-software#725]
If the configured WiFi network is not available during the sensors’ boot process (after power on), the firmware opens an access point for configuration. This is helpful for initial configuration. However, if the WiFi network was already configured previously, and now is not available while the sensor board starts, the admin website of the firmware will be accessible via its own WiFi network. The admin website contains the SSID and password of the configured network - you can see it if you use the browser developer feature "Inspect Element" on the password field, or save the page as HTML and view it there, look for the "wlanpwd" input field.

The password should be transmitted from server to browser as "***". I think this has been discussed for the basic auth password field, but it should be implemented for the WiFi password field as well.

As a workaround to overcome this issue, users should configure basic authentication to protect the admin page, or set an SSID and password for the firmware’s access point. These settings are in the section "only if you really know what you're doing“, but users should be encouraged to use these settings.

**Comment by saper-2** [comment]
Hi,
I am about to build my own sensor, @carstenjahn  thank you for pointing this out, I'll have to not forget to configure security in my sensor 😄 .
Pointing out a problem is good 👍 , but without a idea of solution it's harder on programmer(s) to fix it 😄 , so let me add my "idea", I setup a lot of esp8266 with Tasmota firmware and they have implemented very good solution for this problem:
If the wifi network is not connectable the esp tries looking/connecting to that specified network. If the device running tasmota is powered off 5 times in row it switch back to AP mode, and allow to connect to it's AP and reconfigure it.

So here is my idea based on Tasmota solution:
The sensor will try find & connect to saved wifi network indefinitely.
If it fail to connect, and it will be powered on 5 times without being able to connect to remembered network it should switch then to AP mode with "blank" wifi password. So the "reboot counter" is reset on successful wifi connection (connected to wifi and received IP from DHCP server).
/or/
The sensor will try find & connect to saved wifi network indefinitely.
If I press & hold button "Flash" (NodeMCU board) for e.g. 20sec - the senor will switch to AP mode.

**Comment by dirkmueller** [comment]
I believe I already fixed this issue in the beta firmware:

```
NRZ-2020-130-B4
* Prevent password leakage in configuration dialogs
```

**Comment by dirkmueller** [comment]
Please reopen if there is still an issue with beta firmware.
