### ISSUE TITLE
neu kompilieren

### ISSUE THREAD

**Issue by Gisi0** [opendata-stuttgart/sensors-software#753]
bitte einmal eine neue Version mit aktuellem Framework rausbringen, wegen dem WPA downgrade attack Bug.
[https://github.com/esp8266/Arduino/commit/355b29161481d1ed68436f52a2f30e3c76b9f146](url)

**Comment by dirkmueller** [comment]
I am currently testing the fixed arduino core for compatibility.

**Comment by dirkmueller** [comment]
NRZ-2020-130-B8 or later includes this fix.
