### ISSUE TITLE
Pa Werte

### ISSUE THREAD

**Issue by oe3osb** [opendata-stuttgart/sensors-software#754]
Hallo,
mir ist aufgefallen, dass die Luftdruckwerte vom BME280, die an opensensemap.org gesendet werden, abweichend zu den auf  devices.sensor.community sind (Komma).

**opensense:**
![grafik](https://user-images.githubusercontent.com/29872463/89449872-fd4d8a80-d759-11ea-9e74-c66030ecb4bd.png)

**devices.sensor.community:**
![grafik](https://user-images.githubusercontent.com/29872463/89450265-8e246600-d75a-11ea-8057-b5c91dd2907e.png)

Vielen Dank fuer die Mühe!
Erich

**Comment by imaluschi** [comment]
Da scheint auf devices.sensor.community ein "h" für Hektopascal bei der Anzeige der Einheit zu fehlen. Luftdruck auf Meereshöhe in diesem Fall 101873 Pa = 1018.73 hPa = 1018.73mbar = 1.01873 bar.
Korrekte Einheit bei opensensemap, allerdings ungewohnt zum Lesen.

**Comment by dirkmueller** [comment]
The issue seems to be fixed? I see this on my devices.sensor.community page:

```
Luftdruck: | 984.85 hPa
-- | --
Luftdruck auf Meereshöhe: | 1020.76 hPa
-- | --
```


Please reopen if you still see an issue.

**Comment by ricki-z** [comment]
@oe3osb Since today the site devices.sensor.community is showing the correct unit. I had to find my test device first to verify this ;-)
