### ISSUE TITLE
SDS PM-Sensor not working with NRZ-2020-130-B6

### ISSUE THREAD

**Issue by imaluschi** [opendata-stuttgart/sensors-software#759]
When trying the last beta NRZ-2020-130-B6 (because of using DNMS), i realized that the SDS is not working with this Firmware.

Screenshot with NRZ-2020-130-B6:
![Screenshot_20200824_143029](https://user-images.githubusercontent.com/15073635/91045726-9b28cc80-e617-11ea-908c-9fe4cc200711.png)
Checking cables and all stuff, no chance to get SDS working. Then i tried to upload the last (non-beta) version NRZ-2020-129 - and it worked.
Screenshot with NRZ-2020-129:
![Screenshot_20200824_143436](https://user-images.githubusercontent.com/15073635/91046101-2609c700-e618-11ea-8cc6-370b2e354d4c.png)

Furthermore, to compile (and upload) the beta, some lines had to be commented, "PIN_CS" seems to be defined nowhere (at least for ESP8266).
//        digitalWrite(PIN_CS, HIGH);
//        delay(500);
//        digitalWrite(PIN_CS, LOW);

![Screenshot_20200824_142652](https://user-images.githubusercontent.com/15073635/91045866-cad7d480-e617-11ea-87f1-4b16ea4d3f45.png)

Otherwise nice work, i like the new Config page ;-)

**Comment by imaluschi** [comment]
Sorry, i realized  #737 is the same issue.
For the questions:
Yes, cabling is ok, SDS is working with NRZ-2020-129 but not working with NRZ-2020-130-B6, only firmware-update without touching the device/cables ;-)

**Comment by dirkmueller** [comment]
closing as duplicate to #737.

dies war eine regression von #769 . es wurden global parameter geändert die dazu geführt haben dass die kommunikation mit dem SDS nur noch mit 115200 baud läuft. was mit der alten arduinocore version nicht geht.

das problem ist bereits gefixed.
