### ISSUE TITLE
"An eigene API senden"    ThinkSpeak  - funktioniert nicht 

### ISSUE THREAD

**Issue by MikeMoltoHAJ** [opendata-stuttgart/sensors-software#760]
Hallo - so sehr ich hier auch suche - ich finde keinen Weg meine Daten vom
Feinstaubsensor
Firmware: NRZ-2020-129 
an ThinkSpeak zu senden. Hat vielleicht jemand die korrekten Einträge für die Konfig? 
Bin leider kein Fachmann, habe diverse Einstellungen mehr auf gut Glück versucht, es kommt aber nichts an.

**Comment by MikeMoltoHAJ** [comment]
![Screenshot_2020-08-26 Gerätestatus](https://user-images.githubusercontent.com/48403840/91410447-3fdd2100-e847-11ea-83b7-c6c741a18a6c.png)
![Screenshot_2020-08-26 Konfiguration](https://user-images.githubusercontent.com/48403840/91410464-4370a800-e847-11ea-89e9-1c2ce7be594a.png)

**Comment by ricki-z** [comment]
Unsere Firmware unterstützt ThingSpeak nicht. Wir müssten für jede dieser Plattformen einen extra Format-String abspeichern und dann beim Senden entsprechend mit Werten füllen. Und das auch noch abhängig von den aktiven Sensoren. Bei dem verfügbaren Speicher ist das dann etwas viel verlangt.
Wer Daten an eine andere als die implementierten APIs senden will, kann "An eigene API senden" nutzen, um die Daten an ein Skript zu senden, welches die Daten dann in das benötigte Format umwandelt und dann an z.B. ThingSpeak weiterleitet.
Ein Beispiel-Skript gibt es unter https://github.com/opendata-stuttgart/madavi-api/blob/master/data_simple.php

**Comment by MikeMoltoHAJ** [comment]
Danke für die Antwort. Die Fehlermeldung war weg nachdem ich den Serverstring aufgeteilt habe und ab /update?... in die Pfad Zeile geschrieben habe. Port 443 . Dann werde ich mich im Winter hinsetzen müssen und PHP und Javascript lernen. z.Z keine Ahnung
