### ISSUE TITLE
Sending GPS-Data to InfluxDB

### ISSUE THREAD

**Issue by KoffeinKaio** [opendata-stuttgart/sensors-software#781]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Connect NEO 6M GPS Reciever to Airohr
2. Setup the Sensor to send to InfluxDB
3. ???
4. Profit! ... or maybe not

__Expected behavior:__
Data is successfully sent to influxdb

__Actual behavior:__
InfluxDB replies with an error.
Error only happens when I activate the GPS Reciever.

__Environment info:__

* System info: Firmware NRZ-2020-130-B7/DE (Sep 4 2020 11:59:14) on NodeMCU 2
* InfluxDB version: InfluxDB v1.8.2 (git: 1.8 6a1299e8c6c81ef8fd573ed2b700217121baf04e)

__Logs:__
`
{"error":"unable to parse 'feinstaub,node=esp8266-xxxxxx SDS_P1=6.62,SDS_P2=2.58,BME280_temperature=22.61,BME280_pressure=99671.41,BME280_humidity=61.18,GPS_lat=11.11111,GPS_lon=11.111111,GPS_height=260.00,GPS_date=09/04/2020,GPS_time=19:41:47.00,samples=1097970,min_micro=48,max_micro=4399353,signal=-73': invalid number"}
`

**Comment by ricki-z** [comment]
@KoffeinKaio Please test the latest beta firmware. The problem was the format for GPS_time and GPS_date (non-quoted string). The latest beta should now send both in one string GPS_datetime.

**Comment by KoffeinKaio** [comment]
additional debug:

`
20:56:17.777 -> ## Sending to sensor.community - GPS
20:56:17.824 -> Request failed with error: 400
20:56:17.824 -> Details:{"detail":"JSON parse error - Expecting ',' delimiter: line 1 column 219 (char 218)"}
20:56:17.926 -> ## Sending to madavi.de: 
20:56:18.554 -> Succeeded - api-rrd.madavi.de
20:56:18.554 -> ## Sending to opensensemap: 
20:56:19.485 -> Request failed with error: 400
20:56:19.532 -> Details:{"code":"InvalidContent","message":"Invalid JSON: Unexpected number in JSON at position 466"}

`

**Comment by dirkmueller** [comment]
Fix was merged, can we close this?

**Comment by KoffeinKaio** [comment]
Ill test it with firmware from ota this evening and will close it if it works

**Comment by KoffeinKaio** [comment]
works for me with Firmware version: NRZ-2020-130-B9/EN (Sep 8 2020)
