### ISSUE TITLE
Sensor interface does not state date of firmware

### ISSUE THREAD

**Issue by seb-1204** [opendata-stuttgart/sensors-software#79]
The sensor interface does not show what date/version the firmware is.

It would be good to have a build date shown in the interface.

**Comment by ricki-z** [comment]
Firmware version in shown in the header of all pages. Directly below 'Feinstaubsensor', the ID and the mac address.

**Comment by seb-1204** [comment]
Are you referring to 

> Firmware: NRZ-2017-080

Where would I find the correlating tag/version/release information on github?

PS: do the sensors auto-update themselves?

**Comment by dokape** [comment]
@seb-1204: 
The sensor-firmware has the auto-update-option. It should be activated.
As there was no additional comments since May, 20:
Are your questions answered? 
Can this issue be closed?
