### ISSUE TITLE
Internal Server Error for sensor upload

### ISSUE THREAD

**Issue by chansters** [opendata-stuttgart/sensors-software#795]
My sensor hasn't been able to upload data for past 10 hours or so (since just before 1pm Pacific Standard Time).  https://devices.sensor.community/sensors is showing Internal Server Error.  My sensor # is 49528.

**Comment by ricki-z** [comment]
The main database server is down because of a hardware failure. The restore of nearly 1TByte needs some time.

**Comment by chansters** [comment]
> The main database server is down because of a hardware failure. The restore of nearly 1TByte needs some time.

Thank you !

**Comment by sumerland** [comment]
Does the server issue also explain the gaps in the grafana plots? Opensensemap uploads are not affected.
![Screenshot_20200916-131637-01](https://user-images.githubusercontent.com/64929473/93330587-498eee80-f81f-11ea-85e6-ebf7e8c40f9a.jpeg)

**Comment by sumerland** [comment]
Plots are looking good again. Many thanks for fixing this!
