### ISSUE TITLE
Possible to remove unnecessary DEBUG Info?

### ISSUE THREAD

**Issue by imaluschi** [opendata-stuttgart/sensors-software#811]
Possible to reduce DEBUG-Info when choosing max. Info?
Would give better overview when investigating problems.

![Screenshot_20201018_131748](https://user-images.githubusercontent.com/15073635/96365923-75fe9900-1144-11eb-815e-11da0d669fa5.png)

At least, i don't understand why it is useful to put out the same message every second.
As far as i know SDS is not running during some seconds before the measurements (warming up).

![Screenshot_20201018_132002](https://user-images.githubusercontent.com/15073635/96365958-b3fbbd00-1144-11eb-9058-0713764b878d.png)

It seems every second the DEBUG-Infos is written.

![Screenshot_20201018_132607](https://user-images.githubusercontent.com/15073635/96366079-8ebb7e80-1145-11eb-8faf-0acaacb027c1.png)

Maybe add a DEBUG-message when the SDS is beginning to warm up? And also something like "SDS011-Measurements" when beginning to measure?

**Comment by ricki-z** [comment]
In case of a software crash we need to know what the firmware has done at this moment. Debugging ESP866 firmware is hard enough even with that info.

**Comment by imaluschi** [comment]
I belive it's hard enough.
The problem for me as user is to get informations why something is not working. Would also be helpful for you to get such informations in case of logging an Issue.

For example, i updated my Sensor (SDS011, DHT, BME280, DNMS) from a beta version with the latest release (NRZ-2020-131). Some time later, i saw, that the DHT was not sending data anymore.
Before i file an Issue, i want to have more informations (as you too ;-) ). 

I didn't even touch a cable...

![Screenshot_20201018_131352](https://user-images.githubusercontent.com/15073635/96374173-5f226b80-1171-11eb-9438-6504575e13f8.png)

![Screenshot_20201018_131600](https://user-images.githubusercontent.com/15073635/96374225-a577ca80-1171-11eb-853a-b6d76250690a.png)

Similar on another Device with only DNMS and short time Intervall with sending to an InfluxDB. But much better overview without SDS-messages.

![Screenshot_20201018_173918](https://user-images.githubusercontent.com/15073635/96375059-00f88700-1177-11eb-90cf-c893f6fd651c.png)

![Screenshot_20201018_192501](https://user-images.githubusercontent.com/15073635/96375288-5ed99e80-1178-11eb-9267-17eecd146ff9.png)


I don't know what is possible, but you can imagine that the informations are not very helpful to find a cause.

I will have an eye on these problems and file an Issue in case it occurs more often.

**Comment by dirkmueller** [comment]
@imaluschi I agree that "max info" is usually printing too much info. however, for debugging why there are failures, I think you don't need to set "max info", the default min-info should cover those. 

In cour case we can see the key issue being

DHT11/DHT22 read failed

this is when the sensor doesn't return valid data. can you try powering off this node for like a minute and then powering it on again? does this recover it?

if it doesn't, we might have an issue with the change of default I2C speed that was introduced in 2020-131. which firmware version was the last one that previously worked?

**Comment by imaluschi** [comment]
Ok, thanks, i will use min-info in future.
I filed a new issue concerning the DHT failure - #816 .

For my case, we can close this issue.
