### ISSUE TITLE
I have checked it here. It's working. Can anyone else confirm this problem?

### ISSUE THREAD

**Issue by Ralle2020** [opendata-stuttgart/sensors-software#812]
Sorry, i am new in Github.
After the lastest Update it is impossible to Open the Webpage on my Device.
Only a few records arrived within 1 hour.
I use the following Sensors: SDS011 and HTU21

**Comment by dirkmueller** [comment]
@Ralle2020 can you check if #814 matches your issue?

**Comment by dirkmueller** [comment]
Please follow the conversation in #814
