### ISSUE TITLE
DHT sometimes fails since update to NRZ-2020-131

### ISSUE THREAD

**Issue by imaluschi** [opendata-stuttgart/sensors-software#816]
Since the last update the DHT fails sometimes.

![Screenshot_20201019_080801](https://user-images.githubusercontent.com/15073635/96505369-4dff5a80-1256-11eb-8dea-aea0997e3a62.png)

Today morning (19th of oct.) it was not possible to get the DHT working again with a  sensor restart. Tried it two times with no success. Had to unplug the USB-cable from the power source and after starting the DHT worked again.
![Screenshot_20201019_215657](https://user-images.githubusercontent.com/15073635/96505509-86069d80-1256-11eb-9d09-3a523e0370e7.png)

Today evening i realized that again DHT is not working.
![Screenshot_20201019_215002](https://user-images.githubusercontent.com/15073635/96506599-32954f00-1258-11eb-8173-05fb2e5aeef7.png)

This time it was possible to get it working again with a sensor restart.

Device status from today
![Screenshot_20201019_215055](https://user-images.githubusercontent.com/15073635/96506435-ecd88680-1257-11eb-8fd4-4dcde3044acb.png)

Really don't know what the problem is, no hint by debug-messages, only that the sensor could not be read. The problem occured also yesterday.
But it seems that the problem occured already with NRZ-2020-130-B10/B11 (not sure what version i had on 15.10. and when i updated to B11).

**Comment by imaluschi** [comment]
It's hard to say, with which version the sensor-error occured first, when i read an comment of #789 it seems, that already with NRZ-2020-130B9 have been a problem with DHT.
https://github.com/opendata-stuttgart/sensors-software/issues/789#issuecomment-703054268

**Comment by dirkmueller** [comment]
@imaluschi this issue report shows 0 wifi disconnects over 12 hours, so it is very likely a different problem.

**Comment by imaluschi** [comment]
It seems to be a specific problem with the DHT sensor.
The last two days no action was needed/done, the DHT failed but began to work again.
The high amount of errors sending to sensor.community comes probably from using more sensors than i could register (SDS011 and DNMS are registered, DHT and BME280 not).

![Screenshot_20201020_231549](https://user-images.githubusercontent.com/15073635/96682226-d0803b00-1378-11eb-8ca6-794898151f6f.png)
![Screenshot_20201020_231616](https://user-images.githubusercontent.com/15073635/96682246-d6761c00-1378-11eb-87b0-9807d1c18cbb.png)
![Screenshot_20201021_083336](https://user-images.githubusercontent.com/15073635/96682274-dc6bfd00-1378-11eb-89b9-65af5d8662a0.png)
![Screenshot_20201021_083502](https://user-images.githubusercontent.com/15073635/96682288-e0981a80-1378-11eb-9cbe-97c611b0d93b.png)

And sometimes data of both sensors are not sent (or failure of both?? I don't know), but data were sent because data of DNMS is available during the time of missing DHT/BME values. Same problem or another problem??? Device status as above for that time.
![Screenshot_20201021_084939](https://user-images.githubusercontent.com/15073635/96683679-c19a8800-137a-11eb-95b1-284af9b1f76f.png)
![Screenshot_20201021_085043](https://user-images.githubusercontent.com/15073635/96683690-c5c6a580-137a-11eb-90a8-2807f3ff4ecc.png)

**Comment by imaluschi** [comment]
> @imaluschi this issue report shows 0 wifi disconnects over 12 hours, so it is very likely a different problem.
@dirkmueller, yes i think so too. Some of the problems disappeared since NRZ-2020-130B10 but some remained.
I mentioned my post in the WLAN-Issue here because it seems the DHT-problem occured already (at least) with B9.

![Screenshot_20201021_090456](https://user-images.githubusercontent.com/15073635/96685105-f14a8f80-137c-11eb-92d1-155f39a66806.png)
As you can see, missing data of both sensors was the main problem at this time. Sometimes "only" DHT and BME where missing, somtimes all values (DHT, BME, SDS and DNMS).
DHT errors where minor but present.
![Screenshot_20201021_090615](https://user-images.githubusercontent.com/15073635/96685118-f60f4380-137c-11eb-8ddb-b9aaa1a6c856.png)
![Screenshot_20201021_090741](https://user-images.githubusercontent.com/15073635/96685131-fad3f780-137c-11eb-87e3-814073ab80a7.png)

**Comment by dirkmueller** [comment]
@imaluschi could you please retest with the current OTA in beta channel? Would be good to know if this issue happens to be fixed by that.

**Comment by imaluschi** [comment]
Done. Firmware: NRZ-2020-132-B2/DE (Oct 23 2020)

**Comment by imaluschi** [comment]
Beta-Firmware NRZ-2020-132-B2/DE is not perfect (concerning this issue) but much better.
Some short outages.

![Screenshot_20201103_211735](https://user-images.githubusercontent.com/15073635/98036393-43c68a00-1e1a-11eb-8fb9-9859138a3a33.png)
![Screenshot_20201103_211624](https://user-images.githubusercontent.com/15073635/98036413-4b862e80-1e1a-11eb-8b91-6ca16779774a.png)
![Screenshot_20201103_211831](https://user-images.githubusercontent.com/15073635/98036425-4f19b580-1e1a-11eb-92b6-2f585d81a121.png)

But yesterday again both BME and DNMS stopped working, UI was not very responsive (only sometimes, i think around measurements). More informations in #739 .

**Comment by imaluschi** [comment]
I didn't realize missing DHT values for quite weeks.
Firmware: NRZ-2020-133/DE (Nov 29 2020)
In my opinion we could close this issue.
