### ISSUE TITLE
I can't set the time.The time on the sensors is 3 hours less than in my time zone.Tell me this time where is the server located or my time? And how do I change it if it's my time?

### ISSUE THREAD

**Issue by Anton8998** [opendata-stuttgart/sensors-software#820]
![Безымянный](https://user-images.githubusercontent.com/73285428/96861873-62697000-146d-11eb-964f-1731e2d6517b.png)

**Comment by holgerbohni** [comment]
Hi @Anton8998, as far as I know, you can't change it. All devices are synchronized with UTC, that means your display/app/database has to manage your timezone. If you try to perform some analysis on the data, it's quite useful and simple to have all recorded values in UTC to prevent timezone confusions later on.

**Comment by Anton8998** [comment]
Thanks!

**Comment by dirkmueller** [comment]
@Anton8998 by intention we keep all the sensor.community devices synced in time with UTC. it helps with troubleshooting and with data correlation globally. we do need to keep some time on the devices as they need to validate TLS certificates, so correct system time is essence. 

it should not cause any side effects for anything anywhere however.
