### ISSUE TITLE
fatal error: intl_de.h: No such file or directory

### ISSUE THREAD

**Issue by obitoo55** [opendata-stuttgart/sensors-software#84]
intl_de.h forgotten ?

**Comment by darcoto** [comment]
No.
It is there
https://github.com/opendata-stuttgart/sensors-software/blob/master/airrohr-firmware/intl_de.h

Please check about new folder structure - the files are moved to
https://github.com/opendata-stuttgart/sensors-software/blob/master/airrohr-firmware/

**Comment by ricki-z** [comment]
please close issue if it's solved.
