### ISSUE TITLE
Sensor number on map

### ISSUE THREAD

**Issue by jmdijkstra** [opendata-stuttgart/sensors-software#842]
Dear readers, I am new on the subject and have a question.
Today I have constructed and installed an air measurement sensor as part of community measuring project in Holland named onzelucht.nl (our air)
I have noticed that when I check my sensor on the "Map. Sensor. Community" map, the number indicated on the map on the location where the sensor is installed is not in line with the number given to my by the supplier. The number begins with a #. 
And the location on the map is not exact the real installation location, so I am wondering whether it is my sensor of the one from someone in the neighbourhood.
Can anyone clarify this for me? Thanks in advance,
Joh. Dijkstra

**Comment by pjgueno** [comment]
Hi,
In devices.sensor.community, did you check the checkbox "Publish exact location" ? Otherwise, there is a randomization in a radius of 100 m.
![Capture d’écran 2020-12-05 à 10 29 00](https://user-images.githubusercontent.com/16778931/101239071-00935b80-36e5-11eb-8054-95365ea0fd6a.png)

**Comment by jmdijkstra** [comment]
Dear Pierre- Jean, thanks for the reply. I have corrected it and it's now better.
Regards, Johannes

**Comment by pjgueno** [comment]
Done!
