### ISSUE TITLE
CSV API Option

### ISSUE THREAD

**Issue by Kreid4** [opendata-stuttgart/sensors-software#872]
Hello 
I am fairly new sensor owner.  I am wondering how the CSV API option on the device configuration page works .  Does this mean you can output data/info to a local file? 

Our sensos
https://maps.sensor.community/#14/51.0907/-1.7848

All help, would be appreciated please.
Thank  you

Regards
K

**Comment by ricki-z** [comment]
The CSV option will send the measured values as comma separated values to the serial interface. So you need to connect the NodeMCU directly to a computer. And you need to set the debug level to zero, otherwise there will be debug messages between the data lines.

**Comment by Kreid4** [comment]
Thank you

**Comment by ricki-z** [comment]
@Kreid4 can we close this issue?

**Comment by Kreid4** [comment]
Yes thank you.
Regards
K
