### ISSUE TITLE
Grafana server down?

### ISSUE THREAD

**Issue by MeteorOnEarth** [opendata-stuttgart/sensors-software#876]
Hi, 
I can see that the Grafana server is not displaying data anymore since 15:27 16 Feb 2021
https://api-rrd.madavi.de/grafana/d/q87EBfWGk/temperature-humidity-pressure?orgId=1&var-chipID=esp8266-5013562
I checked other sensors and I am not the only one.
My sensor (locally) still sends data and is connected to Wi-fi

**Comment by ricki-z** [comment]
Granafa (or better the receiving of data at api-rrd.madavi.de) should be up again.
There was an PHP update that disabled the curl module.

**Comment by MeteorOnEarth** [comment]
Thanks, is indeed updating again...
