### ISSUE TITLE
BMP280 is shown in configuration file instead of BME280

### ISSUE THREAD

**Issue by boge717819** [opendata-stuttgart/sensors-software#879]
hello,
my board has a BME280 attached to it, but this is not shown in the tab with "values". Instead the BMP280 is shown with empty values (see screenshot). The latest firmware is used. This happens on different boards and with different BME280's. What am I doing wrong?

thanks in advance,

Etienne

![2021-03-09](https://user-images.githubusercontent.com/38206689/110517939-caaeaa80-810b-11eb-9fd5-8972aaacc489.jpg)

**Comment by pjgueno** [comment]
I had and I have again exactly the same problem: the solderings oydize. Use some Kontakt 60 desoxydizer or some 95% ethanol with a toothbrush to clean gently the pins and solder points. It should start again and be recognized as a BME280.

**Comment by boge717819** [comment]
Hi Pierre-Jean,

this morning I tried your solution and it worked!  I had to resolder the
connections on the BME280. They also were heavily corroded. We are back in
business, thank you very much.

Danke, thanks, merci

Etienne

**Comment by ropeters68** [comment]
You can use a little nail polish to protect the connections.

**Comment by boge717819** [comment]
indeed, nail polish could prevent this. Thanks!

Etienne
