### ISSUE TITLE
Blocking the IP address

### ISSUE THREAD

**Issue by RudyVDWalle** [opendata-stuttgart/sensors-software#882]
I am using the sensor software and I keep losing the connection on the browser because the system resets its IP address. How can I block this? I am talking of the AirRohr sensor system.

**Comment by pjgueno** [comment]
Are you sure it is not coming from your router ? What can you see in the DHCP client list and on the DHCP address attribution options ?

**Comment by RudyVDWalle** [comment]
You are right, I should have known this. Meanwhile I managed to block the IP address. Thks for your comment ù. It helped me to refocus on the issue.
