### ISSUE TITLE
Extreme read out values (issue solved)

### ISSUE THREAD

**Issue by E-Stok** [opendata-stuttgart/sensors-software#899]
Since last night the sensor measures extreme high values:

Sensor | Parameter | Value
-- | -- | --
SDS011 | PM2.5 | 999.9&nbsp;µg/m³
SDS011 | PM10 | 1999.9&nbsp;µg/m³

Is there a defect in the sensor?

Best regards,

**Comment by pjgueno** [comment]
What is the setup ? It seems the sensor produces the max values for both PM10 and PM2.5. Which power supply ?

**Comment by E-Stok** [comment]
It seemed that the input opening of the sensor was dirty. After cleaning I got normal values. Issue solved!
