### ISSUE TITLE
Support setting the timezone of the sensor location

### ISSUE THREAD

**Issue by seb-1204** [opendata-stuttgart/sensors-software#90]
Featurerequest.

Since this project has sensors outside of Germany it would be nice if the sensor software would support setting the timezone in which the sensor is located.

**Comment by TheNitek** [comment]
See https://github.com/opendata-stuttgart/sensors-software/issues/61 ;-)

**Comment by ricki-z** [comment]
Why? All data is saved UTC. The sensor itself doesn't have any real time clock. Time zone could be resolved based on geo location. There are services for this.
