### ISSUE TITLE
Sensor not collecting and transmitting data

### ISSUE THREAD

**Issue by aaaprahamian** [opendata-stuttgart/sensors-software#904]
Hi, I have a sensor ID 2476676. Since 28th it stopped collecting and transmitting data. Firmware version: NRZ-2020-133/EN (Nov 29 2020). Can you please advise how can I troubleshoot the sensor and understand what the issue is and how to fix it? I have not changed anything and the stop is sudden.

**Comment by pjgueno** [comment]
It sends data actually:
![Capture d’écran 2021-06-29 à 19 38 59](https://user-images.githubusercontent.com/16778931/123843117-d4099000-d911-11eb-9bc4-29c30301d985.png)
Can I have you location and/or the ID on the map ?

**Comment by aaaprahamian** [comment]
Hi, thanks for the quick reply. The on the sensor community web page is: 55382. I am also using the aqi.eco but there is no data for sure. Do you think it could be an issue with the aqi? Also when I open directly the IP address of the sensor and go to the current data tan I see no data :(

**Comment by aaaprahamian** [comment]
I am located in Sofia, Bulgaria if this would help.

**Comment by aaaprahamian** [comment]
![Screenshot_20210629-201411](https://user-images.githubusercontent.com/86680574/123844298-842fc680-d91b-11eb-8ce9-8651a2468253.png)

**Comment by pjgueno** [comment]
Incredible ! Both the links are showing data:
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?orgId=1&var-node=55382
https://api-rrd.madavi.de/grafana/d/GUaL5aZMz/pm-sensors?orgId=1&var-chipID=esp8266-2476676
It is a mystery...
Does the hexagon appears on the map at your location? Zoom and send me the url with the hash.

On your last picture, it is normal: you restarted and the time for the first measurement was not reached yet.

**Comment by aaaprahamian** [comment]
Hi, yes the hexagon is still there. Here is the link: https://maps.sensor.community/#16/42.6552/23.2593

As for the data on current data no matter how much time passes there is no data. Also I see that after some time of stand by I am not able to connect to the IP of the sensor and I need to restart it.

**Comment by Petarkir2000** [comment]
@aaaprahamian could you contact hq@airbg.info to find solution?

**Comment by aaaprahamian** [comment]
Will do this now. 👍
