### ISSUE TITLE
Keine Stationen sichtbar

### ISSUE THREAD

**Issue by totocotonio** [opendata-stuttgart/sensors-software#933]
Ich habe gerade die Seite

https://maps.sensor.community/#6/51.402/15.141

aufgerufen.

Es werden keine Stationen angezeigt.

**Comment by ricki-z** [comment]
Hallo,
das war morgens kurz vor 6 Uhr. Gegen 1 Uhr morgens war die Datenbank stehen geblieben, gegen 7 Uhr sollte wieder alles gelaufen sein.
Wir sind ein ehrenamtliches Projekt. Da kann es schon mal vorkommen, daß es kürzere Ausfallzeiten gibt. Und wir vielleicht nicht morgens um 6 Uhr gleich nach dem Aufstehen erst mal alle Systeme prüfen ...
