### ISSUE TITLE
Unplausible Werte nachträglich löschen

### ISSUE THREAD

**Issue by Ableser** [opendata-stuttgart/sensors-software#938]
mein Sensor 21448 hat in der Zeit 
vom 
21.10.21
20:33:33 -147 Celsius, 575 hPa

bis einschließlich
22.10.21
17:23:17 -147 Celsius, 575 hPa

diese unplausiblen Werte für Temperatur 
und Luftfeuchtigkeit
festgestellt (nach Neustart wieder i.O.)
Die Werte befinden sich nun auch 
in den Diagramm und machen die Auswertung unmöglich...

Ich bitte um Löschung dieser Werte, wenn möglich ;-)

**Comment by ricki-z** [comment]
Duplicate of #939
