### ISSUE TITLE
Undocumented Dependency: LiquidCrystal I2C

### ISSUE THREAD

**Issue by dhavlik** [opendata-stuttgart/sensors-software#94]
LiquidCrystal I2C library dependency is not documented. Not sure which version I should use.

**Comment by ricki-z** [comment]
Dependency is added to the Readme.md

**Comment by ricki-z** [comment]
@dhavlik : Can we close this issue?

**Comment by dokape** [comment]
I think we can close this. 
My setup from scratch works with the Readme.
