### ISSUE TITLE
Read Error new DHT22 sensor

### ISSUE THREAD

**Issue by MJLEVER00** [opendata-stuttgart/sensors-software#942]
Hello,

my DHT22 sensor has been giving 99.9% humidity for a long time, so I am trying to replace it with a new one.
However, when I connect it the sensor gives no reading and the debug log says:

## Sending to sensor.community - SDS011
Succeeded - api.sensor.community
DHT11/DHT22 read failed
DHT11/DHT22 read failed
DHT11/DHT22 read failed
DHT11/DHT22 read failed
DHT11/DHT22 read failed

What to do? I have already been toying with it for a while, checking the wire order etc etc. Would be very happy with any suggestions!

Maarten
Amsterdam

**Comment by ricki-z** [comment]
Hello could you please check that the cables are properly connected to the pins of the DHT22?
The pins are really thin so it may help if you bent the pins a little.

**Comment by MJLEVER00** [comment]
Thank you, Ricki-Z. 
I have bent the pins, but it makes no difference. I tried different cables: no difference.
I bought yet another DHT22: same result.
I bought a BME280 hoping it would work: same result (no readings...)
What to do? My room is littered with sensors, I am a bit desperate.
Can it be that I somehow need to "reset" the software in order to forget that old DHT sensor with its forever stuk 99.9% humidity reading? If not, what ELSE could it possible be?

**Comment by pjgueno** [comment]
If you did not connect well at first you can have burnt the pins. I have already seen it.

When you tried with the BME280, did you change the config in the WiFi interface ? Did you use the right pins for SCL and SDA ?

**Comment by MJLEVER00** [comment]
Thanks Pjgueno,
This is how I connected the wires:
SDA -> D3
SCL -> D4
GND -> G
VCC -> 3V
pins CSB and SDO are unused.

Burning the pins: how would I recognise that? I would say I am rather precise and never mis-connected them, but who knows.

Would it make sense to erase the firmware and start the installation all over? Could that make any difference? So far I didn't do that because I was afraid it would somehow break the link with my old sensor data.

Any suggestions much appreciated!

**Comment by pjgueno** [comment]
**Did you select BME instead of DHt22 in the config ?**

![Capture d’écran 2022-01-23 à 12 22 08](https://user-images.githubusercontent.com/16778931/150675978-82dec470-559e-4320-bac6-354c148ae393.png)

Reflash should not be necessary but anyway, you won't "break the link". The board ID is generated from the MAC address of the ESP. It will be the same and actually the config file is persistent.

**Comment by MJLEVER00** [comment]
Yes, I did definately select the BME280 sensor...
Here is with I get:

![bme280](https://user-images.githubusercontent.com/97239719/150676513-b3e458a1-4146-4dff-8d72-f2c3dcc0e70f.jpg)

(It does show up as a BM**P**280 sensor though, might be that it only recognises the BME once it gets its first reading?)

And this is with both new sensors attached:

![dht22_bme280](https://user-images.githubusercontent.com/97239719/150676562-68cb8db5-ea12-4b41-812f-237e18bfb4f4.jpg)

I did notice, by the way, that each DHT22 sensor that I have (I now have 3 of them) looks slightly different. The one is a bit thicker, the other has smaller holes in the casing, etc etc. Could it be that I still haven't found the precise DHT22 type that DOES work? (But then again, what about the BME280?)

**Comment by MJLEVER00** [comment]
Additionally, here are the debug logs for both the DHT22 and the BME280 sensors (for the sake of clarity, only 1 sensor connected each time):

![0C535C42-FB5A-4723-8F15-AD903A8D00FA](https://user-images.githubusercontent.com/97239719/150677828-dd5f4a90-d295-4b75-9dfa-9679addcd2ae.png)

![FD4844FA-6A7F-404A-9413-4E0BE75457F9](https://user-images.githubusercontent.com/97239719/150677832-61207249-989f-47a6-9dd6-39b048ff898e.png)

I have no idea what to do next. Again, suggestions most welcome :)

**Comment by pjgueno** [comment]
It is not normal, that the BME280 is recognized as a BMP280 in such a case.
Try to reflash and send me some  screenshot of each config tab. You are doing something wrong but I can't imagine what...

How come you are sending something to madavi right after the BMx Test ?

![Capture d’écran 2022-01-23 à 13 21 49](https://user-images.githubusercontent.com/16778931/150678160-05572b9b-cf2e-45af-89fd-061a9909070a.png)

**Comment by MJLEVER00** [comment]
Hello Pjgueno,
thanks a lot for your questions.
I did reflash, below are screenshots of all the relevant config tabs. This time with both sensors connected... Same situation... No readings. Suggestions?

Kind regards
Maarten
Amsterdam

(By the way: I have no clue what it is sending if it has no sensor data. I am not familiar with the code...)

![_0device status](https://user-images.githubusercontent.com/97239719/150858786-e476fe0c-51b4-48f8-af08-7c7f63779860.jpg)
![_config_1wifi](https://user-images.githubusercontent.com/97239719/150858788-0dd623cc-14a4-4d9e-8f4e-bcb696fdebb7.jpg)
![_config_2more settings](https://user-images.githubusercontent.com/97239719/150858790-d7cebce5-bc75-43d9-b163-65b106da1895.jpg)
![_config_3sensors](https://user-images.githubusercontent.com/97239719/150858791-b6cf4b78-f90a-494e-b578-27ef5e088cd2.jpg)
![_config_4api](https://user-images.githubusercontent.com/97239719/150858792-1df7667d-f270-41db-b121-49a715447ded.jpg)
![_0current data](https://user-images.githubusercontent.com/97239719/150858794-5435647e-61a3-4940-bf09-6fcc3ffcf516.jpg)

**Comment by stewecar** [comment]
Hello,
did you check the esp8266 3,3V pins voltage? did you check the cables in continuity mode with a multimeter? I had once a lot of damaged cables that did not work well. Check also joint quality and make new welding joints if pins are corroded or not giving enough voltage. Lemme know. Cheers!

**Comment by MJLEVER00** [comment]
Thanks for the suggestion!
Tried it. Stable 3.3 V over both the pins AND the welding joints.
It's so strange...

**Comment by MJLEVER00** [comment]
Solved it (at least most of it).
Bought a new NodeMCU, new shorter cables and whereas both the new DHT22 sensors still don't work, the BME280 does! And now it also appears as a BME280 (no longer as a BMP280).
Thanks, Pjgueno and Stewecar, for your support.
My sensor can go back outside.
