### ISSUE TITLE
sensor BMP presion atmosferica fuera de rango o incorrecta

### ISSUE THREAD

**Issue by Krisdragow** [opendata-stuttgart/sensors-software#956]
### ID: 7965572 (500291798b84)
Versión del Firmware: NRZ-2020-133/ES (Nov 29 2020)

Pressure (hPa): 82068.00 
Temperature (°C): 23.00
----
Sending to sensor.community - BMP180
Succeeded - api.sensor.community
Sending to madavi.de: 
Succeeded - api-rrd.madavi.de
 Sending to Server FS App: 
Succeeded - server.chillibits.com
 Sending to aircms.online: 
Request failed with error: 403

Details:
 Sending to custom influx db: 
Sending to custom api: 
Sending as csv: 
CSV Output: {"software_version": "NRZ-2020-133", "sensordatavalues":[{"value_type":"BMP_pressure",

**Comment by pjgueno** [comment]
It is the serial log not the values which are sent.
We still have not corrected hPa to Pa...
It does not matter actually:
![Capture d’écran 2022-04-02 à 20 22 33](https://user-images.githubusercontent.com/16778931/161396317-c4138af9-15de-4ee6-ac94-a3464497a78f.png)

But maybe you mean the 820 hPa...Are you in the middle of a tornado ? Or do you live at 2000 m altitude ?

**Comment by Krisdragow** [comment]
_But maybe you mean the 820 hPa...Are you in the middle of a tornado ?_  haha it seems like it lol

i done this, just reinstall all the firmware and it works good i think... 
but i forgoten to say, i use the pms5003 and not the sds011, is necesary tu conect RX and TX (PMS5003)?

**Comment by pjgueno** [comment]
You can connect like the sds011.
Check the datasheet of the pms5003 to see the pinout.

Don t forget to select the right sensor everywhere.

**Comment by Krisdragow** [comment]
thx a lot, now all is working good.
