### ISSUE TITLE
Bm280 Request failed with error: 400 Details:["sensor could not be selected."

### ISSUE THREAD

**Issue by babajoux** [opendata-stuttgart/sensors-software#961]
Irgendwie werden die Daten vom Sensor BM280 nicht an die Website weitergeleitet. Ich kann sie sonst normal abrufen und auslesen. 

airRohr: NRZ-2020-133/DE
mounting FS...
opened config file...
parsed json...
output debug text to displays...
Connecting to Tintin
..................SNTP synced: Wed Jul 13 16:44:06 2022

twoStageOTAUpdate
output debug text to displays...
.
WiFi connected, IP is: 192.168.1.112
Starting Webserver... 192.168.1.112

ChipId: 14745287

MAC Id: e8db84e0fec7
Read SDS...: 21-01-12(bdce)
Stopping SDS011...
Read BMxE280...
Trying BMx280 sensor on 76 ... found
Read DNMS...
Trying DNMS sensor on 0x5PM10:  2.97
PM2.5: 0.90
----
## Sending to sensor.community - SDS011
Succeeded - api.sensor.community
Pressure (hPa): 101552.03
Temperature (°C): 30.40
----
## Sending to sensor.community - BMP280
Request failed with error: 400
Details:["sensor could not be selected."]
LAeq: 51.85
LA_MIN: 46.15
LA_MAX: 65.79
----
## Sending to sensor.community - DNMS
Succeeded - api.sensor.community
## Sending to madavi.de: 
Succeeded - api-rrd.madavi.de
## Sending to Server FS App: 
Succeeded - server

**Comment by babajoux** [comment]
![F21D3C73-791E-4819-97C8-C386F0D3D4E0](https://user-images.githubusercontent.com/82976400/178788829-9297dfcf-0752-4bbc-a0b2-f607b48da857.png)
![A08699A7-45E3-4D4B-BBDF-4E58AA4CC13C](https://user-images.githubusercontent.com/82976400/178788836-ffa8acaf-7fd8-46b1-80ba-c57397faf899.jpeg)

**Comment by dokape** [comment]
Can confirm.

Same firmware.

Debug-level max.
Output in Window:

—————————-
PM10 (sec.) : 0.90
PM2.5 (sec.): 0.90
/R SDS011
R/ SDS011
PM10 (sec.) : 1.00
PM2.5 (sec.): 0.90
/R SDS011
R/ SDS011
PM10 (sec.) : 1.00
PM2.5 (sec.): 0.90
/R SDS011
R/ SDS011
PM10 (sec.) : 1.10
PM2.5 (sec.): 1.00
/R SDS011
R/ SDS011
PM10 (sec.) : 1.10
PM2.5 (sec.): 1.00
/R SDS011
PM10:  1.03
PM2.5: 0.93
----
## Sending to sensor.community - SDS011
Succeeded - api.sensor.community
R/ DHT22
Temperature (°C): 32.20
Humidity (%): 42.80
----
/R DHT22
## Sending to sensor.community - DHT22
Request failed with error: 400
Details:["sensor could

**Comment by pjgueno** [comment]
Can we see the config @ devices.sensor.community. Are you sure the same sensors are chosen ?

**Comment by babajoux** [comment]
![80C3D66B-981F-4459-966D-C9F93827C6FF](https://user-images.githubusercontent.com/82976400/178858305-552adc22-8adf-4c65-a51a-630646760672.png)

**Comment by babajoux** [comment]
Ah I see, I chosed the wrong sensor bme280 instead of BMP280. Thank you that solved the issue.

**Comment by pjgueno** [comment]
Gotcha! I knew it. I should write the "SC debug guide".
