### ISSUE TITLE
Particulate matter sensor transmission error

### ISSUE THREAD

**Issue by lytton1** [opendata-stuttgart/sensors-software#964]
The sensor measures the values, but they are no longer displayed on the map 

2 errors are displayed in the device status
OTA Return | connection failed

Data Send Return | connection failed

does anyone have an explanation

**Comment by pjgueno** [comment]
Can you send both the config in devices.Sensor.community and in the Sensor itself.
Can you also get the usb Logs ?

**Comment by lytton1** [comment]
Hello, I'm not an expert but I hope this is the correct data

 

I haven't changed any of the previous settings either

 

 



 



 

 



 

 

Best regards

Walter

 

Von: Pierre-Jean Guéno ***@***.***> 
Gesendet: Samstag, 10. September 2022 18:13
An: opendata-stuttgart/sensors-software ***@***.***>
Cc: lytton1 ***@***.***>; Author ***@***.***>
Betreff: Re: [opendata-stuttgart/sensors-software] Particulate matter sensor transmission error (Issue #964)

 

Can you send both the config in devices.Sensor.community and in the Sensor itself.
Can you also get the usb Logs ?

**Comment by pjgueno** [comment]
I can't see your pictures...

**Comment by lytton1** [comment]
Good Morning,

 

is available again

on this position

 



 

Von: Pierre-Jean Guéno ***@***.***> 
Gesendet: Montag, 12. September 2022 09:04
An: opendata-stuttgart/sensors-software ***@***.***>
Cc: lytton1 ***@***.***>; Author ***@***.***>
Betreff: Re: [opendata-stuttgart/sensors-software] Particulate matter sensor transmission error (Issue #964)

 

I can't see your pictures...

**Comment by lytton1** [comment]
Hello Pierre-Jean problem is solvedThe cause was the last update from homeassistantThank you for your supportBest regardsWalterVon meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Pierre-Jean Guéno ***@***.***>Datum: Sa., 10. Sept. 2022, 18:13An: opendata-stuttgart/sensors-software ***@***.***>Cc: lytton1 ***@***.***>, Author ***@***.***>Betreff: Re: [opendata-stuttgart/sensors-software] Particulate matter sensor transmission error (Issue #964)
Can you send both the config in devices.Sensor.community and in the Sensor itself.
Can you also get the usb Logs ?

**Comment by pjgueno** [comment]
Autoupdate of an home assistant
