### ISSUE TITLE
My sensor doesn't work any more

### ISSUE THREAD

**Issue by joebar72** [opendata-stuttgart/sensors-software#966]
In the last 3 months PM2,5 and PM10 data are not collected correctly (absent data). The temperature and humidity fine. What can I do? The restart doesn't work:

https://www.madavi.de/sensor/graph.php?sensor=esp8266-1543953-sds011

Thanks
Joe

**Comment by pjgueno** [comment]
Please compare the configurations in both the sensor itself and devices.sensor.community. Is the PM sensor the same ?

Then check the connections. A cable could be loose among the four.

**Comment by joebar72** [comment]
Thanks
It may be the second one...I only open the box and touched the connections. Now the sensor is working fine.
Regards
Joe

**Comment by pjgueno** [comment]
It's almost always the Dupont cables... For my own projects I ve conpletely stopped to use them

**Comment by pjgueno** [comment]
Bad connections
