### ISSUE TITLE
Ticker.h missing

### ISSUE THREAD

**Issue by andi98** [opendata-stuttgart/sensors-software#97]
Hallo!

Wir haben gerade versucht, die Airrohr-Firmware selber zu kompilieren, aber leider fehlt wohl eine Bibliothek. Es fehlt die Datei `Ticker.h`. Wie heißt denn die Bibliothek, in der die liegt?

Dankeschön schonmal!

Liebe Grüße,
Andi

**Comment by ricki-z** [comment]
Die Ticker.h gehört zur esp8266-Erweiterung. Habt ihr diese nach dem Eintrag der URL über den Board-Manager installiert?
