### ISSUE TITLE
license violation

### ISSUE THREAD

**Issue by jonasstein** [opendata-stuttgart/sensors-software#98]
please check the file
https://github.com/opendata-stuttgart/sensors-software/blob/master/airrohr-firmware/pdf/sds_dht_wiring.pdf
it uses non free material.

**Comment by ricki-z** [comment]
PDF ist removed. It was a first draft for a documentation.

**Comment by dokape** [comment]
Which part was not licenced? 
The images of DHT and/or SDS011? 
Or the pinout of the nodeMCU?
In Case of pinout nodeMCU the wiki should be checked to:

https://github.com/opendata-stuttgart/meta/wiki/Pinouts-NodeMCU-v2,-v3

In case of image for DHT and SDS I can make some new images.

**Comment by ricki-z** [comment]
The mentioned pdf was removed. It was was first draft for our 'manual' and someone used images from aliexpress. We don't need this pdf anymore.

**Comment by dokape** [comment]
Can this issue be closed?

**Comment by jonasstein** [comment]
yes, the file was removed. I close it for the developers here.
