### ISSUE TITLE
Platformio Firmware compilation fails (SSD1306 library missing)

### ISSUE THREAD

**Issue by alexschultze** [opendata-stuttgart/sensors-software#984]
Warning! Could not find the package with 'ESP8266_SSD1306 @ 4.1.0' requirements for your system 'windows_amd64'

**Comment by alexschultze** [comment]
Potential workaround:
Replace library in platformio with:
thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ 4.3.0

**Comment by pjgueno** [comment]
Isn't it already like this ?

**Comment by pjgueno** [comment]
Please PR in Develop!

**Comment by pjgueno** [comment]
@ricki-z Do you understand the issue ?

**Comment by Phaze-III** [comment]
> Please PR in Develop!

Hi @pjgueno , this concerns the current master branch, the platformio.ini in the beta* branches is OK
