### ISSUE TITLE
SEN5X PM measurement is not working

### ISSUE THREAD

**Issue by Wolfy82x** [opendata-stuttgart/sensors-software#993]
Hello All,
I have an Issue, after a few weeks of use the PM measurement suddenly stopped working
![pm01](https://user-images.githubusercontent.com/132517695/236058053-b80537ae-5be2-4109-a2f6-182db8e6795a.PNG)
![pm02](https://user-images.githubusercontent.com/132517695/236058148-73ea9ac1-62d2-4fe3-b939-83a24f78ec57.PNG)

It is 0 after several restarts. How can I debug, or solve this problem?

Thank you!

**Comment by Wolfy82x** [comment]
Fixed, sensor was clogged :S

**Comment by pjgueno** [comment]
solved
